// STORMTILT captain "brisa", candidate C: superellipsoid vinyl blocks.
// Rig contract: joints torso/head/hat/armL/armR/legL/legR are Groups at the joint (zero rest rotation),
// handL/handR palm markers; all on g.userData.joints. Faces +Z, base at y = 0. Generated by the 404 loop.
export default function (THREE) {
  // ---- CONTESSA BRISA: slim duelist, navy and gold naval tailcoat, black tricorn with a white plume, white gloves, tall black boots ----
  const D = { H: 1.85, hip: 0.92, legY: 0.9, legX: 0.1, shX: 0.26, shY: 1.36, neck: 1.4, headTop: 1.81, hatTilt: 0.08, splay: 0.14, handY: 0.54 };
  function dress(K) {
    const navy = M(0x1f2a55, { roughness: 0.35 }), gold = M(0xc9a043, { roughness: 0.3, metalness: 0.75 }), black = M(0x16161c, { roughness: 0.4 });
    const bootM = M(0x101014, { roughness: 0.18 }), white = M(0xf6f3ea, { roughness: 0.45 }), hairM = M(0x1d1b22, { roughness: 0.45 });
    const skin = M(0xf3cdb0, { roughness: 0.5 }), cheek = M(0xeb9d98, { roughness: 0.6 }), ink = M(0x15110f, { roughness: 0.2 }), lipM = M(0xc0504d, { roughness: 0.4 });
    const plume = M(0xf8f6f0, { roughness: 0.7 });
    // legs: slim trousers in tall glossy boots
    K.trousers(black, { y0: 0.02, y1: -0.4, r: 0.085 });
    K.boots(bootM, black, { top: -0.38, r: 0.098, w: 0.1, len: 0.34, toeZ: 0.05, soleH: 0.045, cuffMat: bootM });
    const b = -D.legY;
    legs(black, K.tube(0.104, 0.104, 0.035, 14), [0, b + 0.13, 0.0]);
    legs(gold, new THREE.BoxGeometry(0.05, 0.045, 0.02), [0.03, b + 0.13, 0.1], [0, 0.3, 0]);
    // tailcoat (torso-local, hips at 0)
    K.coat(navy, { y0: -0.1, y1: 0.4, rx: 0.21, rz: 0.155, hemR: 0.215, shH: 0.08 });
    sym('torso', navy, new THREE.BoxGeometry(0.15, 0.42, 0.03), [0.085, -0.25, -0.13], [0.18, -0.12, 0]);
    sym('torso', gold, new THREE.BoxGeometry(0.015, 0.42, 0.034), [0.16, -0.25, -0.125], [0.18, -0.12, 0]);
    sym('torso', gold, new THREE.BoxGeometry(0.15, 0.015, 0.034), [0.085, -0.455, -0.093], [0.18, -0.12, 0]);
    sym('torso', gold, new THREE.BoxGeometry(0.018, 0.5, 0.02), [0.1, 0.15, 0.142], [0, 0.55, 0]);
    for (let i = 0; i < 4; i++) sym('torso', gold, K.blob(0.013, 0.013, 0.01, 6, 4), [0.06, 0.06 + i * 0.075, 0.155]);
    sym('torso', gold, new THREE.BoxGeometry(0.11, 0.03, 0.025), [0.17, -0.06, 0.1], [0, 0.85, 0]);
    put('torso', navy, new THREE.TorusGeometry(0.09, 0.035, 6, 14), [0, 0.46, -0.01], [Math.PI / 2 - 0.2, 0, 0]);
    put('torso', gold, new THREE.TorusGeometry(0.09, 0.012, 4, 14, Math.PI), [0, 0.475, 0.0], [Math.PI / 2 - 0.2, 0, Math.PI]);
    put('torso', white, K.blob(0.07, 0.035, 0.035, 8, 6), [0, 0.43, 0.12]);
    put('torso', white, K.blob(0.05, 0.05, 0.03, 8, 6), [0, 0.37, 0.14], [0.3, 0, 0]);
    // arms: navy sleeves, deep gold cuffs, white gloves
    K.sleeves(navy, { len: 0.42, r: 0.07, cuffMat: gold });
    arms(white, K.tube(0.07, 0.06, 0.06, 10), [0, -0.46, 0]);
    K.hands(white, { s: 1.2 });
    // head: rosy cheeks, smile, monocle
    const hd = { cy: 0.21, rx: 0.16, ry: 0.2, rz: 0.165, chin: -0.07 };
    K.headBase(skin, hd);
    sym('head', ink, K.blob(0.024, 0.034, 0.014, 8, 6), [0.06, 0.235, 0.146 + K.fz]);
    sym('head', white, K.blob(0.007, 0.007, 0.005, 5, 4), [0.066, 0.248, 0.158 + K.fz]);
    sym('head', hairM, K.cap(0.01, 0.05, 6), [0.065, 0.29, 0.138 + K.fz], [0, 0, Math.PI / 2 + 0.2]);
    sym('head', cheek, K.blob(0.035, 0.025, 0.012, 8, 6), [0.1, 0.18, 0.135 + K.fz], [0, 0.6, 0]);
    put('head', skin, K.blob(0.026, 0.036, 0.03, 8, 6), [0, 0.2, 0.17 + K.fz]);
    put('head', lipM, new THREE.TorusGeometry(0.035, 0.008, 4, 10, Math.PI), [0, 0.15, 0.152 + K.fz], [0.25, 0, Math.PI]);
    put('head', gold, new THREE.TorusGeometry(0.038, 0.007, 4, 14), [-0.06, 0.235, 0.155 + K.fz], [-0.1, -0.35, 0]);
    put('head', gold, K.tube(0.003, 0.003, 0.2, 4), [-0.1, 0.12, 0.13 + K.fz], [0, 0, -0.15]);
    // long wavy black hair: cap over the back, waves down to the shoulders
    K.hairCap(hairM, hd, 0.72, 1.07);
    for (let i = 0; i < 7; i++) {
      const a = Math.PI * 0.5 + (i / 6) * Math.PI;
      put('head', hairM, K.blob(0.065, 0.11, 0.06, 8, 6), [Math.sin(a) * 0.15, 0.08 + (i % 2) * 0.02, Math.cos(a) * 0.12 - 0.02], [0, a, 0]);
    }
    sym('head', hairM, K.blob(0.04, 0.09, 0.045, 8, 6), [0.155, 0.08, 0.0]);
    put('head', hairM, K.blob(0.15, 0.05, 0.08, 10, 6), [0, 0.37, 0.08], [0.4, 0, 0]);
    // tricorn: crown + three upturned brim panels (one point to the front), gold edge, white plume
    const k = 1.12, R = 0.27 * k;
    if (K.style === 'B') putHat(black, lathe([[0, 0.07], [0.09, 0.065], [0.15, 0.03], [0.175, -0.04], [0.18, -0.09], [0, -0.09]].map(([r, y]) => [r * k, y]), 18));
    else if (K.style === 'C') putHat(black, K.sq(0.18 * k, 0.08, 0.18 * k, 0.85, 0.6, 0.85, 18, 10), [0, -0.01, 0]);
    else { putHat(black, new THREE.SphereGeometry(0.18 * k, 18, 6, 0, Math.PI * 2, 0, Math.PI / 2), [0, -0.03, 0], null, [1, 0.55, 1]); putHat(black, K.tube(0.18 * k, 0.18 * k, 0.06, 18), [0, -0.06, 0]); }
    putHat(black, new THREE.CylinderGeometry(R, R, 0.02, 3), [0, -0.09, 0]);
    for (let i = 0; i < 3; i++) {
      const a = Math.PI / 3 + i * (2 * Math.PI / 3), d = R * 0.5, w = R * Math.sqrt(3) * 0.98;
      const pos = [Math.sin(a) * d, -0.04, Math.cos(a) * d];
      const pan = new THREE.BoxGeometry(w, 0.12, 0.025); pan.translate(0, 0.05, 0); pan.rotateX(0.32);
      putHat(black, pan, [pos[0], -0.09, pos[2]], [0, a, 0]);
      const edge = new THREE.BoxGeometry(w * 0.98, 0.018, 0.032); edge.translate(0, 0.11, 0); edge.rotateX(0.32);
      putHat(gold, edge, [pos[0], -0.09, pos[2]], [0, a, 0]);
    }
    putHat(gold, K.blob(0.025, 0.025, 0.012, 8, 6), [0.1, 0.0, 0.11], [0, 0.6, 0]);
    // plume sweeping up and back from the left of the crown
    putHat(plume, K.blob(0.045, 0.13, 0.03, 8, 6), [0.13, 0.08, 0.02], [-0.5, 0, -0.35]);
    putHat(plume, K.blob(0.035, 0.09, 0.025, 8, 6), [0.16, 0.18, -0.06], [-1.0, 0, -0.3]);
    putHat(plume, K.blob(0.025, 0.06, 0.02, 6, 5), [0.17, 0.22, -0.14], [-1.6, 0, -0.2]);
  }

  // ---- rig core: identical in every STORMTILT captain ----
  // Joints are Groups placed AT the joint with zero rest rotation; geometry hangs off them,
  // merged per joint per material (one mesh per colour per moving part).
  const V3 = THREE.Vector3;
  const g = new THREE.Group();
  g.name = 'captain';
  const matCache = new Map();
  function M(hex, o) {
    o = o || {};
    const key = hex + '|' + JSON.stringify(o);
    if (!matCache.has(key)) {
      const m = new THREE.MeshStandardMaterial(Object.assign({ color: hex, roughness: 0.32, metalness: 0, side: THREE.DoubleSide }, o));
      matCache.set(key, m);
    }
    return matCache.get(key);
  }
  const W = {}, J = {};
  function joint(name, parent, wx, wy, wz) {
    const o = new THREE.Group();
    o.name = name;
    W[name] = new V3(wx, wy, wz);
    const pw = parent ? W[parent] : new V3();
    o.position.set(wx - pw.x, wy - pw.y, wz - pw.z);
    (parent ? J[parent] : g).add(o);
    J[name] = o;
  }
  joint('torso', null, 0, D.hip, 0);
  joint('head', 'torso', 0, D.neck, 0);
  joint('hat', 'head', 0, D.headTop, 0);
  joint('armL', 'torso', D.shX, D.shY, 0);
  joint('armR', 'torso', -D.shX, D.shY, 0);
  joint('legL', null, D.legX, D.legY, 0);
  joint('legR', null, -D.legX, D.legY, 0);

  const B = new Map();
  const _e = new THREE.Euler(), _q = new THREE.Quaternion();
  function TRS(p, r, s) {
    _e.set(r ? r[0] : 0, r ? r[1] : 0, r ? r[2] : 0);
    _q.setFromEuler(_e);
    return new THREE.Matrix4().compose(new V3(p ? p[0] : 0, p ? p[1] : 0, p ? p[2] : 0), _q.clone(), new V3(s ? s[0] : 1, s ? s[1] : 1, s ? s[2] : 1));
  }
  function add(jn, mat, geo, localM) {
    let q = geo.index ? geo.toNonIndexed() : geo;
    q.deleteAttribute('uv');
    if (!q.attributes.normal) q.computeVertexNormals();
    q.applyMatrix4(localM);
    const k = jn + '|' + mat.uuid;
    if (!B.has(k)) B.set(k, { jn, mat, list: [] });
    B.get(k).list.push(q);
  }
  const mir = (p, sd) => (p ? [p[0] * sd, p[1], p[2]] : null);
  const mirR = (r, sd) => (r ? [r[0], r[1] * sd, r[2] * sd] : null);
  // joint-local placement
  function put(jn, mat, geo, p, r, s) { add(jn, mat, geo, TRS(p, r, s)); }
  // a mirrored pair on one joint (x and -x)
  function sym(jn, mat, geo, p, r, s) { for (const sd of [1, -1]) put(jn, mat, geo.clone(), mir(p, sd), mirR(r, sd), s); }
  // arm frame: origin at the shoulder, the arm hangs along -y, splayed out by D.splay
  function armFrame(sd) { return new THREE.Matrix4().makeRotationZ(sd * D.splay); }
  function putArm(sd, mat, geo, p, r, s) { add(sd > 0 ? 'armL' : 'armR', mat, geo, armFrame(sd).multiply(TRS(mir(p, sd), mirR(r, sd), s))); }
  function arms(mat, geo, p, r, s) { putArm(1, mat, geo.clone(), p, r, s); putArm(-1, mat, geo, p, r, s); }
  // legs: origin at each hip joint
  function putLeg(sd, mat, geo, p, r, s) { put(sd > 0 ? 'legL' : 'legR', mat, geo, mir(p, sd), mirR(r, sd), s); }
  function legs(mat, geo, p, r, s) { putLeg(1, mat, geo.clone(), p, r, s); putLeg(-1, mat, geo, p, r, s); }

  // hat frame: tilted back by D.hatTilt about the top of the head (positive tips the front brim up)
  function putHat(mat, geo, p, r, s) { add('hat', mat, geo, new THREE.Matrix4().makeRotationX(-(D.hatTilt || 0)).multiply(TRS(p, r, s))); }
  function symHat(mat, geo, p, r, s) { for (const sd of [1, -1]) putHat(mat, geo.clone(), mir(p, sd), mirR(r, sd), s); }
  function mergeList(list) {
    let n = 0;
    for (const q of list) n += q.attributes.position.count;
    const P = new Float32Array(n * 3), N = new Float32Array(n * 3);
    let o = 0;
    for (const q of list) { P.set(q.attributes.position.array, o * 3); N.set(q.attributes.normal.array, o * 3); o += q.attributes.position.count; }
    const r = new THREE.BufferGeometry();
    r.setAttribute('position', new THREE.BufferAttribute(P, 3));
    r.setAttribute('normal', new THREE.BufferAttribute(N, 3));
    r.computeBoundingSphere();
    return r;
  }
  function lathe(pts, seg) { return new THREE.LatheGeometry(pts.map((a) => new THREE.Vector2(Math.max(0.0005, a[0]), a[1])), seg || 16); }

  function finish() {
    for (const { jn, mat, list } of B.values()) {
      const m = new THREE.Mesh(mergeList(list), mat);
      m.castShadow = true; m.receiveShadow = true; m.name = jn + '_part';
      J[jn].add(m);
    }
    // palm markers, in the arm frame
    const hands = {};
    for (const sd of [1, -1]) {
      const h = new THREE.Object3D();
      h.name = sd > 0 ? 'handL' : 'handR';
      h.position.set(0, -D.handY, D.handZ || 0).applyMatrix4(armFrame(sd));
      J[sd > 0 ? 'armL' : 'armR'].add(h);
      hands[h.name] = h;
    }
    const measure = () => {
      const box = new THREE.Box3(), v = new V3();
      g.updateMatrixWorld(true);
      g.traverse((n) => {
        const p = n.isMesh && n.geometry.attributes.position; if (!p) return;
        for (let i = 0; i < p.count; i++) box.expandByPoint(v.fromBufferAttribute(p, i).applyMatrix4(n.matrixWorld));
      });
      return box;
    };
    // exact height: every joint has zero rest rotation, so scaling joint offsets and geometry is exact
    let box = measure();
    const k = D.H / (box.max.y - box.min.y);
    g.traverse((n) => { if (n === g) return; n.position.multiplyScalar(k); if (n.isMesh) { n.position.set(0, 0, 0); n.geometry.scale(k, k, k); n.geometry.computeBoundingSphere(); } });
    box = measure();
    const c = box.getCenter(new V3());
    g.children.forEach((o) => { o.position.x -= c.x; o.position.y -= box.min.y; o.position.z -= c.z; });
    g.userData.joints = { torso: J.torso, head: J.head, hat: J.hat, armL: J.armL, armR: J.armR, legL: J.legL, legR: J.legR, handL: hands.handL, handR: hands.handR };
    return g;
  }
  const K = { THREE, D, M, put, sym, putArm, arms, putLeg, legs, putHat, symHat, lathe, TRS, J };

  // ---- body kit C: superellipsoid vinyl blocks (sphere vertices remapped into rounded boxes) ----
  K.style = 'C';
  K.fz = 0.014;
  // pxz shapes the plan (1 = round, 0.4 = boxy), py the profile; taper scales the top relative to the bottom
  const sq = (rx, ry, rz, pxz, py, taper, ws, hs) => {
    const q = new THREE.SphereGeometry(1, ws || 12, hs || 8), a = q.attributes.position;
    const f = (t, p) => Math.sign(t) * Math.pow(Math.abs(t), p);
    for (let i = 0; i < a.count; i++) {
      const x = a.getX(i), y = a.getY(i), z = a.getZ(i);
      const k = taper ? 1 + (taper - 1) * (y + 1) / 2 : 1;
      a.setXYZ(i, f(x, pxz) * rx * k, f(y, py) * ry, f(z, pxz) * rz * k);
    }
    q.computeVertexNormals();
    return q;
  };
  K.sq = sq;
  K.blob = (rx, ry, rz, ws, hs) => sq(rx, ry, rz, 0.9, 0.9, 1, ws || 12, hs || 9);
  K.tube = (rBot, rTop, h, seg) => sq(Math.max(rBot, rTop), h / 2, Math.max(rBot, rTop), 1, 0.3, rTop / Math.max(rBot, rTop), seg || 14, 10);
  K.cap = (r, len, seg) => sq(r, len / 2 + r, r, 1, 0.75, 1, seg || 10, 10);
  K.trousers = (mat, o) => {
    const h = o.y0 - o.y1;
    legs(mat, sq(o.r, h / 2 + 0.02, o.r, 0.85, 0.45, 1 / (o.taper || 0.9), 12, 8), [0, (o.y0 + o.y1) / 2, 0]);
  };
  K.boots = (mat, sole, o) => {
    const b = -D.legY, sh = o.soleH || 0.05;
    const shaftH = o.top - (b + 0.08);
    legs(mat, sq(o.r * 1.02, shaftH / 2, o.r * 1.02, 0.8, 0.4, 0.96, 12, 8), [0, b + 0.08 + shaftH / 2, 0]);
    legs(mat, sq(o.w, 0.095, o.len / 2, 0.7, 0.75, 1, 14, 8), [0, b + sh + 0.045, o.toeZ]);
    legs(sole, sq(o.w * 1.06, sh / 2, o.len / 2 * 1.04, 0.6, 0.25, 1, 16, 6), [0, b + sh / 2, o.toeZ]);
    if (o.cuffMat) legs(o.cuffMat, sq(o.r * 1.16, 0.035, o.r * 1.16, 0.8, 0.4, 1, 14, 6), [0, o.top - 0.02, 0]);
  };
  K.coat = (mat, o) => {
    const h = o.y1 - o.y0, sh = o.shH || 0.1, full = h + sh;
    const bk = o.belly ? 1.08 : 1;
    put('torso', mat, sq(o.hemR * bk, full / 2, o.rz * (o.hemR / o.rx) * bk * (o.belly ? 1.06 : 1), 0.62, 0.55, o.rx / o.hemR, 18, 13), [0, o.y0 + full / 2, 0]);
  };
  K.sleeves = (mat, o) => {
    arms(mat, sq(o.r * 1.04, o.len / 2 + 0.02, o.r * 1.04, 0.85, 0.6, 1.0, 10, 8), [0, -o.len / 2 + 0.02, 0]);
    if (o.cuffMat) arms(o.cuffMat, sq(o.r * 1.16, 0.03, o.r * 1.16, 0.85, 0.4, 1, 12, 6), [0, -o.len + 0.03, 0]);
  };
  K.hands = (mat, o) => {
    const y = -D.handY, s = o.s || 1;
    arms(mat, sq(0.04 * s, 0.085 * s, 0.068 * s, 0.7, 0.8, 1, 10, 8), [0, y + 0.0, 0]);
    arms(mat, sq(0.022 * s, 0.045 * s, 0.022 * s, 1, 0.8, 1, 8, 8), [-0.022 * s, y + 0.01, 0.065 * s], [0.6, 0, -0.5]);
  };
  K.hairCap = (mat, hd, th, k, ph0, phL) => {
    const q = new THREE.SphereGeometry(1, 14, 8, ph0 === undefined ? Math.PI : ph0, phL || Math.PI, 0, Math.PI * th), a = q.attributes.position;
    const f = (t, p) => Math.sign(t) * Math.pow(Math.abs(t), p), tp = 1 - (hd.chin || 0) * 2;
    for (let i = 0; i < a.count; i++) { const x = a.getX(i), y = a.getY(i), z = a.getZ(i), kk = 1 + (tp - 1) * (y + 1) / 2; a.setXYZ(i, f(x, 0.86) * kk, f(y, 0.86), f(z, 0.86) * kk); }
    q.computeVertexNormals();
    put('head', mat, q, [0, hd.cy, 0], null, [hd.rx * k, hd.ry * k, hd.rz * k]);
  };
  K.headBase = (mat, o) => {
    put('head', mat, sq(o.rx, o.ry, o.rz, 0.86, 0.86, 1 - (o.chin || 0) * 2, 18, 13), [0, o.cy, 0]);
    put('head', mat, K.tube(0.06, 0.06, 0.1, 10), [0, 0.03, 0]);
    sym('head', mat, K.blob(0.03, 0.045, 0.025, 8, 6), [o.rx * 0.98, o.cy - 0.01, -0.01]);
  };

  dress(K);
  return finish();
}
