// STORMTILT captain "barnacle", candidate A: assembled primitives (sphere, cylinder, capsule).
// Rig contract: joints torso/head/hat/armL/armR/legL/legR are Groups at the joint (zero rest rotation),
// handL/handR palm markers; all on g.userData.joints. Faces +Z, base at y = 0. Generated by the 404 loop.
export default function (THREE) {
  // ---- BOSUN BARNACLE: huge barrel-chested, grey beard, knitted blue jumper, maroon beanie, brown boots with barnacles ----
  const D = { H: 1.85, hip: 0.8, legY: 0.78, legX: 0.15, shX: 0.4, shY: 1.3, neck: 1.38, headTop: 1.8, hatTilt: 0.05, splay: 0.24, handY: 0.56 };
  function dress(K) {
    const blue = M(0x3550a8, { roughness: 0.8 }), blueDk = M(0x26397e, { roughness: 0.85 }), navy = M(0x1c2440, { roughness: 0.6 });
    const brown = M(0x5a3420, { roughness: 0.45 }), brownDk = M(0x3a2214, { roughness: 0.6 }), shell = M(0xe6dfcc, { roughness: 0.7 });
    const maroon = M(0x7a2328, { roughness: 0.8 }), maroonDk = M(0x5e1a1f, { roughness: 0.85 });
    const skin = M(0xf0c09a, { roughness: 0.5 }), nose = M(0xe0806c, { roughness: 0.45 }), cheek = M(0xe79a8e, { roughness: 0.6 });
    const grey = M(0x9a9a96, { roughness: 0.75 }), greyLt = M(0xb8b8b2, { roughness: 0.75 }), ink = M(0x15110f, { roughness: 0.2 }), white = M(0xf8f4ea, { roughness: 0.3 });
    // legs: short and thick
    K.trousers(navy, { y0: 0.02, y1: -0.46, r: 0.13 });
    K.boots(brown, brownDk, { top: -0.44, r: 0.13, w: 0.135, len: 0.42, toeZ: 0.06, soleH: 0.06, cuffMat: brownDk });
    // barnacles: clusters on the toes and sides of the boots
    const b = -D.legY;
    const spots = [[0.06, 0.12, 0.2], [-0.05, 0.1, 0.22], [0.0, 0.14, 0.17], [0.12, 0.1, 0.08], [0.12, 0.2, 0.0], [-0.11, 0.13, 0.05], [0.04, 0.25, 0.1]];
    for (const [x, y, z] of spots) {
      legs(shell, K.tube(0.026, 0.014, 0.028, 6), [x, b + y, z + 0.06], [Math.atan2(z, 0.2) * 0.8, 0, -x * 4]);
    }
    // barrel jumper
    K.coat(blue, { y0: -0.14, y1: 0.46, rx: 0.37, rz: 0.29, hemR: 0.33, shH: 0.13, belly: true, neckR: 0.1 });
    put('torso', blueDk, K.tube(0.345, 0.345, 0.08, 22), [0, -0.12, 0], null, [1, 1, 0.84]);
    put('torso', blue, new THREE.TorusGeometry(0.12, 0.06, 7, 16), [0, 0.6, 0], [Math.PI / 2, 0, 0], [1, 0.9, 1]);
    // knit cables down the front and back
    for (const x of [-0.18, -0.06, 0.06, 0.18]) {
      for (const zs of [1, -1]) put('torso', blueDk, new THREE.BoxGeometry(0.028, 0.44, 0.03), [x, 0.17, zs * (0.305 - Math.abs(x) * 0.4)], [zs * -0.12, zs * x * 1.6, 0]);
    }
    // arms
    K.sleeves(blue, { len: 0.44, r: 0.105, cuffMat: blueDk });
    K.hands(skin, { s: 1.45 });
    // head: big red nose, rosy cheeks, full grey beard
    const hd = { cy: 0.2, rx: 0.18, ry: 0.2, rz: 0.18 };
    K.headBase(skin, hd);
    sym('head', ink, K.blob(0.025, 0.034, 0.015, 8, 6), [0.065, 0.25, 0.155 + K.fz]);
    sym('head', white, K.blob(0.008, 0.008, 0.006, 5, 4), [0.071, 0.262, 0.168 + K.fz]);
    sym('head', grey, K.cap(0.022, 0.06, 6), [0.072, 0.31, 0.14 + K.fz], [0, 0, Math.PI / 2 + 0.15]);
    sym('head', cheek, K.blob(0.04, 0.03, 0.015, 8, 6), [0.11, 0.18, 0.14 + K.fz], [0, 0.6, 0]);
    put('head', nose, K.blob(0.05, 0.05, 0.05, 12, 8), [0, 0.19, 0.185 + K.fz]);
    put('head', grey, K.blob(0.2, 0.17, 0.13, 12, 8), [0, 0.06, 0.08 + K.fz]);
    put('head', grey, K.blob(0.14, 0.09, 0.1, 12, 8), [0, -0.05, 0.12 + K.fz]);
    sym('head', greyLt, K.blob(0.07, 0.03, 0.04, 8, 6), [0.05, 0.135, 0.18 + K.fz], [0, 0, -0.35]);
    K.hairCap(grey, hd, 0.62, 1.04);
    sym('head', grey, K.blob(0.04, 0.08, 0.07, 8, 6), [0.165, 0.18, 0.02]);
    // beanie with a turned-up rib band (hat-local, top of the head at 0)
    const k = 1.08;
    if (K.style === 'A') {
      putHat(maroon, new THREE.SphereGeometry(0.19 * k, 20, 8, 0, Math.PI * 2, 0, Math.PI / 2), [0, -0.06, 0], null, [1, 0.85, 1]);
      putHat(maroonDk, K.tube(0.205 * k, 0.2 * k, 0.1, 20), [0, -0.1, 0]);
    } else if (K.style === 'B') {
      const p = [[0.2, -0.15], [0.225, -0.14], [0.225, -0.06], [0.205, -0.05], [0.2, 0.0], [0.17, 0.06], [0.12, 0.1], [0.05, 0.115], [0, 0.118]].map(([r, y]) => [r * k, y]);
      putHat(maroon, lathe(p.slice(3), 22));
      putHat(maroonDk, lathe(p.slice(0, 4), 22));
    } else {
      putHat(maroon, K.sq(0.2 * k, 0.13, 0.2 * k, 0.9, 0.75, 0.82, 18, 10), [0, -0.02, 0]);
      putHat(maroonDk, K.sq(0.218 * k, 0.05, 0.218 * k, 1, 0.35, 1, 18, 6), [0, -0.1, 0]);
    }
    for (let i = 0; i < 10; i++) {
      const a = (i / 10) * Math.PI * 2;
      putHat(maroon, new THREE.BoxGeometry(0.02, 0.08, 0.012), [Math.sin(a) * 0.209 * k, -0.1, Math.cos(a) * 0.209 * k], [0, a, 0]);
    }
  }

  // ---- rig core: identical in every STORMTILT captain ----
  // Joints are Groups placed AT the joint with zero rest rotation; geometry hangs off them,
  // merged per joint per material (one mesh per colour per moving part).
  const V3 = THREE.Vector3;
  const g = new THREE.Group();
  g.name = 'captain';
  const matCache = new Map();
  function M(hex, o) {
    o = o || {};
    const key = hex + '|' + JSON.stringify(o);
    if (!matCache.has(key)) {
      const m = new THREE.MeshStandardMaterial(Object.assign({ color: hex, roughness: 0.32, metalness: 0, side: THREE.DoubleSide }, o));
      matCache.set(key, m);
    }
    return matCache.get(key);
  }
  const W = {}, J = {};
  function joint(name, parent, wx, wy, wz) {
    const o = new THREE.Group();
    o.name = name;
    W[name] = new V3(wx, wy, wz);
    const pw = parent ? W[parent] : new V3();
    o.position.set(wx - pw.x, wy - pw.y, wz - pw.z);
    (parent ? J[parent] : g).add(o);
    J[name] = o;
  }
  joint('torso', null, 0, D.hip, 0);
  joint('head', 'torso', 0, D.neck, 0);
  joint('hat', 'head', 0, D.headTop, 0);
  joint('armL', 'torso', D.shX, D.shY, 0);
  joint('armR', 'torso', -D.shX, D.shY, 0);
  joint('legL', null, D.legX, D.legY, 0);
  joint('legR', null, -D.legX, D.legY, 0);

  const B = new Map();
  const _e = new THREE.Euler(), _q = new THREE.Quaternion();
  function TRS(p, r, s) {
    _e.set(r ? r[0] : 0, r ? r[1] : 0, r ? r[2] : 0);
    _q.setFromEuler(_e);
    return new THREE.Matrix4().compose(new V3(p ? p[0] : 0, p ? p[1] : 0, p ? p[2] : 0), _q.clone(), new V3(s ? s[0] : 1, s ? s[1] : 1, s ? s[2] : 1));
  }
  function add(jn, mat, geo, localM) {
    let q = geo.index ? geo.toNonIndexed() : geo;
    q.deleteAttribute('uv');
    if (!q.attributes.normal) q.computeVertexNormals();
    q.applyMatrix4(localM);
    const k = jn + '|' + mat.uuid;
    if (!B.has(k)) B.set(k, { jn, mat, list: [] });
    B.get(k).list.push(q);
  }
  const mir = (p, sd) => (p ? [p[0] * sd, p[1], p[2]] : null);
  const mirR = (r, sd) => (r ? [r[0], r[1] * sd, r[2] * sd] : null);
  // joint-local placement
  function put(jn, mat, geo, p, r, s) { add(jn, mat, geo, TRS(p, r, s)); }
  // a mirrored pair on one joint (x and -x)
  function sym(jn, mat, geo, p, r, s) { for (const sd of [1, -1]) put(jn, mat, geo.clone(), mir(p, sd), mirR(r, sd), s); }
  // arm frame: origin at the shoulder, the arm hangs along -y, splayed out by D.splay
  function armFrame(sd) { return new THREE.Matrix4().makeRotationZ(sd * D.splay); }
  function putArm(sd, mat, geo, p, r, s) { add(sd > 0 ? 'armL' : 'armR', mat, geo, armFrame(sd).multiply(TRS(mir(p, sd), mirR(r, sd), s))); }
  function arms(mat, geo, p, r, s) { putArm(1, mat, geo.clone(), p, r, s); putArm(-1, mat, geo, p, r, s); }
  // legs: origin at each hip joint
  function putLeg(sd, mat, geo, p, r, s) { put(sd > 0 ? 'legL' : 'legR', mat, geo, mir(p, sd), mirR(r, sd), s); }
  function legs(mat, geo, p, r, s) { putLeg(1, mat, geo.clone(), p, r, s); putLeg(-1, mat, geo, p, r, s); }

  // hat frame: tilted back by D.hatTilt about the top of the head (positive tips the front brim up)
  function putHat(mat, geo, p, r, s) { add('hat', mat, geo, new THREE.Matrix4().makeRotationX(-(D.hatTilt || 0)).multiply(TRS(p, r, s))); }
  function symHat(mat, geo, p, r, s) { for (const sd of [1, -1]) putHat(mat, geo.clone(), mir(p, sd), mirR(r, sd), s); }
  function mergeList(list) {
    let n = 0;
    for (const q of list) n += q.attributes.position.count;
    const P = new Float32Array(n * 3), N = new Float32Array(n * 3);
    let o = 0;
    for (const q of list) { P.set(q.attributes.position.array, o * 3); N.set(q.attributes.normal.array, o * 3); o += q.attributes.position.count; }
    const r = new THREE.BufferGeometry();
    r.setAttribute('position', new THREE.BufferAttribute(P, 3));
    r.setAttribute('normal', new THREE.BufferAttribute(N, 3));
    r.computeBoundingSphere();
    return r;
  }
  function lathe(pts, seg) { return new THREE.LatheGeometry(pts.map((a) => new THREE.Vector2(Math.max(0.0005, a[0]), a[1])), seg || 16); }

  function finish() {
    for (const { jn, mat, list } of B.values()) {
      const m = new THREE.Mesh(mergeList(list), mat);
      m.castShadow = true; m.receiveShadow = true; m.name = jn + '_part';
      J[jn].add(m);
    }
    // palm markers, in the arm frame
    const hands = {};
    for (const sd of [1, -1]) {
      const h = new THREE.Object3D();
      h.name = sd > 0 ? 'handL' : 'handR';
      h.position.set(0, -D.handY, D.handZ || 0).applyMatrix4(armFrame(sd));
      J[sd > 0 ? 'armL' : 'armR'].add(h);
      hands[h.name] = h;
    }
    const measure = () => {
      const box = new THREE.Box3(), v = new V3();
      g.updateMatrixWorld(true);
      g.traverse((n) => {
        const p = n.isMesh && n.geometry.attributes.position; if (!p) return;
        for (let i = 0; i < p.count; i++) box.expandByPoint(v.fromBufferAttribute(p, i).applyMatrix4(n.matrixWorld));
      });
      return box;
    };
    // exact height: every joint has zero rest rotation, so scaling joint offsets and geometry is exact
    let box = measure();
    const k = D.H / (box.max.y - box.min.y);
    g.traverse((n) => { if (n === g) return; n.position.multiplyScalar(k); if (n.isMesh) { n.position.set(0, 0, 0); n.geometry.scale(k, k, k); n.geometry.computeBoundingSphere(); } });
    box = measure();
    const c = box.getCenter(new V3());
    g.children.forEach((o) => { o.position.x -= c.x; o.position.y -= box.min.y; o.position.z -= c.z; });
    g.userData.joints = { torso: J.torso, head: J.head, hat: J.hat, armL: J.armL, armR: J.armR, legL: J.legL, legR: J.legR, handL: hands.handL, handR: hands.handR };
    return g;
  }
  const K = { THREE, D, M, put, sym, putArm, arms, putLeg, legs, putHat, symHat, lathe, TRS, J };

  // ---- body kit A: assembled primitives (sphere, cylinder, capsule) ----
  K.style = 'A';
  K.fz = 0;
  K.blob = (rx, ry, rz, ws, hs) => { const s = new THREE.SphereGeometry(1, ws || 12, hs || 9); s.scale(rx, ry, rz); return s; };
  K.tube = (rBot, rTop, h, seg) => new THREE.CylinderGeometry(rTop, rBot, h, seg || 14);
  K.cap = (r, len, seg) => new THREE.CapsuleGeometry(r, len, 3, seg || 8);
  K.trousers = (mat, o) => {
    legs(mat, K.tube(o.r * (o.taper || 0.92), o.r, o.y0 - o.y1), [0, (o.y0 + o.y1) / 2, 0]);
    legs(mat, K.blob(o.r * 0.95, o.r * 0.6, o.r * 0.95, 12, 8), [0, o.y1, 0]);
  };
  K.boots = (mat, sole, o) => {
    const b = -D.legY, sh = o.soleH || 0.05;
    legs(mat, K.tube(o.r * 1.04, o.r, o.top - (b + 0.1)), [0, (o.top + b + 0.1) / 2, 0]);
    legs(mat, K.blob(o.w, 0.1, o.len / 2), [0, b + sh + 0.04, o.toeZ]);
    legs(sole, K.tube(1, 1, sh, 16), [0, b + sh / 2, o.toeZ], null, [o.w * 1.06, 1, (o.len / 2) * 1.04]);
    if (o.cuffMat) legs(o.cuffMat, K.tube(o.r * 1.12, o.r * 1.14, 0.06), [0, o.top - 0.02, 0]);
  };
  K.coat = (mat, o) => {
    const h = o.y1 - o.y0, sz = o.rz / o.rx;
    put('torso', mat, K.tube(o.hemR, o.rx, h, 20), [0, o.y0 + h / 2, 0], null, [1, 1, sz]);
    put('torso', mat, new THREE.SphereGeometry(o.rx, 20, 7, 0, Math.PI * 2, 0, Math.PI / 2), [0, o.y1, 0], null, [1, (o.shH || 0.1) / o.rx, sz]);
    if (o.belly) put('torso', mat, K.blob(o.rx * 1.02, h * 0.42, o.rz * 1.18, 18, 12), [0, o.y0 + h * 0.45, 0.02]);
  };
  K.sleeves = (mat, o) => {
    arms(mat, K.cap(o.r, o.len - o.r, 12), [0, -o.len / 2 + 0.02, 0]);
    if (o.cuffMat) arms(o.cuffMat, K.tube(o.r * 1.12, o.r * 1.12, 0.05, 12), [0, -o.len + 0.03, 0]);
  };
  K.hands = (mat, o) => {
    const y = -D.handY, s = o.s || 1;
    arms(mat, K.blob(0.042 * s, 0.07 * s, 0.07 * s, 10, 8), [0, y + 0.02 * s, 0]);
    for (let i = 0; i < 3; i++) arms(mat, K.blob(0.02 * s, 0.045 * s, 0.02 * s, 8, 6), [0.004, y - 0.06 * s, (0.04 - i * 0.038) * s], [0, 0, 0.12]);
    arms(mat, K.blob(0.021 * s, 0.045 * s, 0.021 * s, 8, 6), [-0.025 * s, y + 0.0, 0.07 * s], [0.6, 0, -0.5]);
  };
  K.hairCap = (mat, hd, th, k, ph0, phL) => put('head', mat, new THREE.SphereGeometry(1, 14, 8, ph0 === undefined ? Math.PI : ph0, phL || Math.PI, 0, Math.PI * th), [0, hd.cy, 0], null, [hd.rx * k, hd.ry * k, hd.rz * k]);
  K.headBase = (mat, o) => {
    put('head', mat, K.blob(o.rx, o.ry, o.rz, 18, 13), [0, o.cy, 0]);
    put('head', mat, K.tube(0.06, 0.06, 0.1, 10), [0, 0.03, 0]);
    sym('head', mat, K.blob(0.03, 0.045, 0.025, 8, 6), [o.rx * 0.98, o.cy - 0.01, -0.01]);
  };

  dress(K);
  return finish();
}
