// STORMTILT captain "player", candidate B: lathe profiles.
// Rig contract: joints torso/head/hat/armL/armR/legL/legR are Groups at the joint (zero rest rotation),
// handL/handR palm markers; all on g.userData.joints. Faces +Z, base at y = 0. Generated by the 404 loop.
export default function (THREE) {
  // ---- PLAYER: young captain, red oilskin, yellow sou'wester, dark trousers, black boots ----
  const D = { H: 1.85, hip: 0.86, legY: 0.84, legX: 0.125, shX: 0.3, shY: 1.28, neck: 1.33, headTop: 1.77, hatTilt: 0.22, splay: 0.15, handY: 0.55 };
  function dress(K) {
    const red = M(0xd7372f, { roughness: 0.22 }), redDk = M(0xa82822, { roughness: 0.3 }), yel = M(0xf2b630, { roughness: 0.25 });
    const navy = M(0x1f2a44, { roughness: 0.6 }), boot = M(0x1b1c20, { roughness: 0.28 }), sole = M(0x0c0c0e, { roughness: 0.6 });
    const skin = M(0xf1c7a0, { roughness: 0.5 }), nose = M(0xeaa27e, { roughness: 0.5 }), hair = M(0x5a3622, { roughness: 0.6 });
    const ink = M(0x15110f, { roughness: 0.2 }), white = M(0xf8f4ea, { roughness: 0.3 });
    const brass = M(0xc9a043, { roughness: 0.3, metalness: 0.7 }), strap = M(0x23262e, { roughness: 0.5 });
    // legs (leg-local, hip joint at 0)
    K.trousers(navy, { y0: 0.02, y1: -0.5, r: 0.108 });
    K.boots(boot, sole, { top: -0.48, r: 0.118, w: 0.12, len: 0.4, toeZ: 0.055, soleH: 0.055 });
    // coat (torso-local, hip pivot at 0)
    K.coat(red, { y0: -0.16, y1: 0.4, rx: 0.265, rz: 0.19, hemR: 0.29, shH: 0.09 });
    put('torso', redDk, new THREE.BoxGeometry(0.035, 0.6, 0.03), [0, 0.1, 0.18]);
    for (const y of [-0.02, 0.12, 0.26]) put('torso', brass, K.tube(0.018, 0.018, 0.075, 8), [0, y, 0.2], [0, 0, Math.PI / 2]);
    sym('torso', redDk, new THREE.BoxGeometry(0.11, 0.035, 0.03), [0.15, -0.04, 0.155], [0, 0.6, 0]);
    put('torso', redDk, new THREE.BoxGeometry(0.03, 0.3, 0.03), [0, -0.06, -0.185]);
    put('torso', redDk, new THREE.BoxGeometry(0.4, 0.03, 0.03), [0, 0.3, -0.17], [-0.3, 0, 0]);
    put('torso', red, new THREE.TorusGeometry(0.105, 0.045, 6, 16), [0, 0.47, -0.005], [Math.PI / 2, 0, 0], [1, 0.9, 1]);
    sym('torso', red, new THREE.BoxGeometry(0.09, 0.1, 0.03), [0.07, 0.42, 0.15], [-0.3, 0, -0.5]);
    // arms (shoulder frame)
    K.sleeves(red, { len: 0.44, r: 0.085, cuffMat: redDk });
    K.hands(skin, { s: 1.35 });
    // head (neck joint at 0)
    const hd = { cy: 0.225, rx: 0.19, ry: 0.215, rz: 0.19, chin: -0.04 };
    K.headBase(skin, hd);
    sym('head', ink, K.blob(0.031, 0.044, 0.018, 10, 8), [0.07, 0.26, 0.163 + K.fz]);
    sym('head', white, K.blob(0.009, 0.009, 0.006, 6, 4), [0.078, 0.277, 0.179 + K.fz]);
    sym('head', hair, K.cap(0.014, 0.06, 6), [0.075, 0.325, 0.153 + K.fz], [0, 0, Math.PI / 2 + 0.18]);
    put('head', nose, K.blob(0.042, 0.048, 0.05, 12, 8), [0, 0.205, 0.193 + K.fz]);
    const teeth = new THREE.SphereGeometry(0.07, 14, 6, 0, Math.PI * 2, Math.PI / 2, Math.PI / 2);
    put('head', white, teeth, [0, 0.14, 0.158 + K.fz], [0.3, 0, 0], [1, 0.6, 0.42]);
    const lip = new THREE.SphereGeometry(0.077, 14, 6, 0, Math.PI * 2, Math.PI / 2, Math.PI / 2);
    put('head', ink, lip, [0, 0.142, 0.153 + K.fz], [0.3, 0, 0], [1, 0.68, 0.42]);
    K.hairCap(hair, hd, 0.62, 1.05);
    sym('head', hair, K.blob(0.028, 0.06, 0.045, 8, 6), [0.175, 0.27, 0.04]);
    put('head', hair, K.blob(0.12, 0.05, 0.07, 10, 6), [0.03, 0.39, 0.1], [0.3, 0, 0.1]);
    put('head', strap, new THREE.TorusGeometry(0.2, 0.01, 4, 16, Math.PI * 1.1), [0, 0.25, 0.04], [0, 0, Math.PI - 0.05 * Math.PI], [1, 1.12, 1]);
    // sou'wester (hat-local, top of the head at 0); back brim longer and lower
    const k = 1.16;
    if (K.style === 'A') {
      putHat(yel, new THREE.SphereGeometry(0.182 * k, 22, 9, 0, Math.PI * 2, 0, Math.PI / 2), [0, -0.03, 0], null, [1, 0.72, 1.04]);
      putHat(yel, K.tube(0.186 * k, 0.182 * k, 0.08, 22), [0, -0.07, 0], null, [1, 1, 1.04]);
      putHat(yel, new THREE.CylinderGeometry(0.185 * k, 0.29 * k, 0.075, 26, 1, true), [0, -0.145, -0.02], [-0.1, 0, 0], [1, 1, 1.06]);
      putHat(yel, new THREE.TorusGeometry(0.29 * k, 0.015, 5, 26), [0, -0.18, -0.025], [Math.PI / 2 - 0.1, 0, 0], [1, 1.06, 1]);
    } else if (K.style === 'B') {
      const p = [[0, 0.1], [0.08, 0.095], [0.145, 0.065], [0.18, 0.005], [0.188, -0.095], [0.215, -0.12], [0.29, -0.165], [0.31, -0.185], [0.3, -0.2], [0.28, -0.19], [0.2, -0.145], [0.172, -0.12]].map(([r, y]) => [r * k, y]);
      putHat(yel, lathe(p, 26), [0, 0, -0.02], [-0.1, 0, 0], [1, 1, 1.05]);
    } else {
      putHat(yel, K.sq(0.185 * k, 0.13, 0.192 * k, 0.85, 0.6, 0.86, 20, 14), [0, -0.03, 0]);
      putHat(yel, K.sq(0.3 * k, 0.022, 0.315 * k, 1, 0.5, 1, 26, 8), [0, -0.145, -0.025], [-0.1, 0, 0]);
    }
  }

  // ---- rig core: identical in every STORMTILT captain ----
  // Joints are Groups placed AT the joint with zero rest rotation; geometry hangs off them,
  // merged per joint per material (one mesh per colour per moving part).
  const V3 = THREE.Vector3;
  const g = new THREE.Group();
  g.name = 'captain';
  const matCache = new Map();
  function M(hex, o) {
    o = o || {};
    const key = hex + '|' + JSON.stringify(o);
    if (!matCache.has(key)) {
      const m = new THREE.MeshStandardMaterial(Object.assign({ color: hex, roughness: 0.32, metalness: 0, side: THREE.DoubleSide }, o));
      matCache.set(key, m);
    }
    return matCache.get(key);
  }
  const W = {}, J = {};
  function joint(name, parent, wx, wy, wz) {
    const o = new THREE.Group();
    o.name = name;
    W[name] = new V3(wx, wy, wz);
    const pw = parent ? W[parent] : new V3();
    o.position.set(wx - pw.x, wy - pw.y, wz - pw.z);
    (parent ? J[parent] : g).add(o);
    J[name] = o;
  }
  joint('torso', null, 0, D.hip, 0);
  joint('head', 'torso', 0, D.neck, 0);
  joint('hat', 'head', 0, D.headTop, 0);
  joint('armL', 'torso', D.shX, D.shY, 0);
  joint('armR', 'torso', -D.shX, D.shY, 0);
  joint('legL', null, D.legX, D.legY, 0);
  joint('legR', null, -D.legX, D.legY, 0);

  const B = new Map();
  const _e = new THREE.Euler(), _q = new THREE.Quaternion();
  function TRS(p, r, s) {
    _e.set(r ? r[0] : 0, r ? r[1] : 0, r ? r[2] : 0);
    _q.setFromEuler(_e);
    return new THREE.Matrix4().compose(new V3(p ? p[0] : 0, p ? p[1] : 0, p ? p[2] : 0), _q.clone(), new V3(s ? s[0] : 1, s ? s[1] : 1, s ? s[2] : 1));
  }
  function add(jn, mat, geo, localM) {
    let q = geo.index ? geo.toNonIndexed() : geo;
    q.deleteAttribute('uv');
    if (!q.attributes.normal) q.computeVertexNormals();
    q.applyMatrix4(localM);
    const k = jn + '|' + mat.uuid;
    if (!B.has(k)) B.set(k, { jn, mat, list: [] });
    B.get(k).list.push(q);
  }
  const mir = (p, sd) => (p ? [p[0] * sd, p[1], p[2]] : null);
  const mirR = (r, sd) => (r ? [r[0], r[1] * sd, r[2] * sd] : null);
  // joint-local placement
  function put(jn, mat, geo, p, r, s) { add(jn, mat, geo, TRS(p, r, s)); }
  // a mirrored pair on one joint (x and -x)
  function sym(jn, mat, geo, p, r, s) { for (const sd of [1, -1]) put(jn, mat, geo.clone(), mir(p, sd), mirR(r, sd), s); }
  // arm frame: origin at the shoulder, the arm hangs along -y, splayed out by D.splay
  function armFrame(sd) { return new THREE.Matrix4().makeRotationZ(sd * D.splay); }
  function putArm(sd, mat, geo, p, r, s) { add(sd > 0 ? 'armL' : 'armR', mat, geo, armFrame(sd).multiply(TRS(mir(p, sd), mirR(r, sd), s))); }
  function arms(mat, geo, p, r, s) { putArm(1, mat, geo.clone(), p, r, s); putArm(-1, mat, geo, p, r, s); }
  // legs: origin at each hip joint
  function putLeg(sd, mat, geo, p, r, s) { put(sd > 0 ? 'legL' : 'legR', mat, geo, mir(p, sd), mirR(r, sd), s); }
  function legs(mat, geo, p, r, s) { putLeg(1, mat, geo.clone(), p, r, s); putLeg(-1, mat, geo, p, r, s); }

  // hat frame: tilted back by D.hatTilt about the top of the head (positive tips the front brim up)
  function putHat(mat, geo, p, r, s) { add('hat', mat, geo, new THREE.Matrix4().makeRotationX(-(D.hatTilt || 0)).multiply(TRS(p, r, s))); }
  function symHat(mat, geo, p, r, s) { for (const sd of [1, -1]) putHat(mat, geo.clone(), mir(p, sd), mirR(r, sd), s); }
  function mergeList(list) {
    let n = 0;
    for (const q of list) n += q.attributes.position.count;
    const P = new Float32Array(n * 3), N = new Float32Array(n * 3);
    let o = 0;
    for (const q of list) { P.set(q.attributes.position.array, o * 3); N.set(q.attributes.normal.array, o * 3); o += q.attributes.position.count; }
    const r = new THREE.BufferGeometry();
    r.setAttribute('position', new THREE.BufferAttribute(P, 3));
    r.setAttribute('normal', new THREE.BufferAttribute(N, 3));
    r.computeBoundingSphere();
    return r;
  }
  function lathe(pts, seg) { return new THREE.LatheGeometry(pts.map((a) => new THREE.Vector2(Math.max(0.0005, a[0]), a[1])), seg || 16); }

  function finish() {
    for (const { jn, mat, list } of B.values()) {
      const m = new THREE.Mesh(mergeList(list), mat);
      m.castShadow = true; m.receiveShadow = true; m.name = jn + '_part';
      J[jn].add(m);
    }
    // palm markers, in the arm frame
    const hands = {};
    for (const sd of [1, -1]) {
      const h = new THREE.Object3D();
      h.name = sd > 0 ? 'handL' : 'handR';
      h.position.set(0, -D.handY, D.handZ || 0).applyMatrix4(armFrame(sd));
      J[sd > 0 ? 'armL' : 'armR'].add(h);
      hands[h.name] = h;
    }
    const measure = () => {
      const box = new THREE.Box3(), v = new V3();
      g.updateMatrixWorld(true);
      g.traverse((n) => {
        const p = n.isMesh && n.geometry.attributes.position; if (!p) return;
        for (let i = 0; i < p.count; i++) box.expandByPoint(v.fromBufferAttribute(p, i).applyMatrix4(n.matrixWorld));
      });
      return box;
    };
    // exact height: every joint has zero rest rotation, so scaling joint offsets and geometry is exact
    let box = measure();
    const k = D.H / (box.max.y - box.min.y);
    g.traverse((n) => { if (n === g) return; n.position.multiplyScalar(k); if (n.isMesh) { n.position.set(0, 0, 0); n.geometry.scale(k, k, k); n.geometry.computeBoundingSphere(); } });
    box = measure();
    const c = box.getCenter(new V3());
    g.children.forEach((o) => { o.position.x -= c.x; o.position.y -= box.min.y; o.position.z -= c.z; });
    g.userData.joints = { torso: J.torso, head: J.head, hat: J.hat, armL: J.armL, armR: J.armR, legL: J.legL, legR: J.legR, handL: hands.handL, handR: hands.handR };
    return g;
  }
  const K = { THREE, D, M, put, sym, putArm, arms, putLeg, legs, putHat, symHat, lathe, TRS, J };

  // ---- body kit B: lathe profiles swept about each part's own axis ----
  K.style = 'B';
  K.fz = 0;
  const arc = (rx, ry, n, a0, a1, cy) => { const p = []; for (let i = 0; i <= n; i++) { const t = a0 + (a1 - a0) * i / n; p.push([rx * Math.sin(t), (cy || 0) - ry * Math.cos(t)]); } return p; };
  K.blob = (rx, ry, rz, ws) => { const q = lathe(arc(1, 1, 8, 0, Math.PI), ws || 12); q.scale(rx, ry, rz); return q; };
  K.tube = (rBot, rTop, h, seg) => lathe([[0, -h / 2], [rBot * 0.9, -h / 2], [rBot, -h / 2 + Math.min(0.015, h * 0.2)], [rTop, h / 2 - Math.min(0.015, h * 0.2)], [rTop * 0.9, h / 2], [0, h / 2]], seg || 14);
  K.cap = (r, len, seg) => { const p = arc(r, r, 4, 0, Math.PI / 2, -len / 2).concat(arc(r, r, 4, Math.PI / 2, Math.PI, len / 2)); return lathe(p, seg || 8); };
  // a lathe swept about +z (for feet): profile [r, along], flattened in y by fy
  const latheZ = (pts, seg, fx, fy) => { const q = lathe(pts, seg || 14); q.rotateX(Math.PI / 2); q.scale(fx || 1, fy || 1, 1); return q; };
  K.trousers = (mat, o) => {
    const t = o.taper || 0.9, h = o.y0 - o.y1;
    legs(mat, lathe([[0, o.y0], [o.r, o.y0], [o.r * 1.04, o.y0 - h * 0.35], [o.r * 0.98 * (1 + t) / 2, o.y0 - h * 0.6], [o.r * t, o.y1 + 0.02], [o.r * t * 0.7, o.y1 - 0.02], [0, o.y1 - 0.03]], 14));
  };
  K.boots = (mat, sole, o) => {
    const b = -D.legY, sh = o.soleH || 0.05, r = o.r;
    legs(mat, lathe([[0, b + 0.08], [r * 1.06, b + 0.08], [r * 1.02, b + 0.2], [r, o.top - 0.04], [r * 1.12, o.top - 0.02], [r * 1.12, o.top], [r * 0.85, o.top + 0.005], [0, o.top]], 16));
    // foot: profile along z from heel to toe, widest at the ball
    const L = o.len, foot = [[0, -L / 2], [o.w * 0.75, -L / 2 + 0.01], [o.w * 0.95, -L / 2 + L * 0.2], [o.w, L * 0.1], [o.w * 0.88, L * 0.3], [o.w * 0.55, L / 2 - 0.015], [0, L / 2]];
    legs(mat, latheZ(foot, 16, 1, 0.1 / o.w), [0, b + sh + 0.045, o.toeZ]);
    const soleP = foot.map(([a, z]) => [a * 1.06, z * 1.04]);
    const sq = latheZ(soleP, 16, 1, 1); sq.scale(1, (sh / 2) / o.w, 1);
    legs(sole, sq, [0, b + sh / 2, o.toeZ]);
    if (o.cuffMat) legs(o.cuffMat, lathe([[r * 1.0, o.top - 0.06], [r * 1.16, o.top - 0.05], [r * 1.18, o.top + 0.0], [r * 1.0, o.top + 0.01]], 16));
  };
  K.coat = (mat, o) => {
    const h = o.y1 - o.y0, sz = o.rz / o.rx, rx = o.rx, sh = o.shH || 0.1;
    const p = [[0, o.y0], [o.hemR * 0.96, o.y0], [o.hemR, o.y0 + 0.02], [(o.hemR + rx) / 2 * (o.belly ? 1.12 : 1), o.y0 + h * 0.4], [rx * (o.belly ? 1.05 : 1), o.y0 + h * 0.75], [rx, o.y1 - 0.02]];
    for (let i = 1; i <= 5; i++) { const t = (i / 5) * Math.PI / 2; p.push([Math.max(o.neckR || 0.07, rx * Math.cos(t)), o.y1 + sh * Math.sin(t)]); }
    p.push([0, o.y1 + sh]);
    put('torso', mat, lathe(p, 22), null, null, [1, 1, o.belly ? sz * 1.08 : sz]);
  };
  K.sleeves = (mat, o) => {
    const r = o.r, L = o.len;
    arms(mat, lathe([[0, 0.05], [r * 0.7, 0.045], [r * 0.98, 0.0], [r * 1.02, -L * 0.4], [r * 1.08, -L + 0.06], [r * 1.12, -L + 0.01], [r * 0.85, -L], [0, -L]], 12));
    if (o.cuffMat) arms(o.cuffMat, lathe([[r * 1.0, -L + 0.06], [r * 1.16, -L + 0.05], [r * 1.18, -L + 0.0], [r * 0.9, -L - 0.005]], 12));
  };
  K.hands = (mat, o) => {
    const y = -D.handY, s = o.s || 1;
    const mit = lathe([[0, 0.07], [0.04, 0.065], [0.062, 0.02], [0.066, -0.04], [0.055, -0.085], [0.03, -0.105], [0, -0.11]], 12);
    mit.scale(0.62 * s, s, s);
    arms(mat, mit, [0, y + 0.02 * s, 0]);
    arms(mat, K.cap(0.022 * s, 0.05 * s, 8), [-0.022 * s, y + 0.0, 0.065 * s], [0.6, 0, -0.5]);
  };
  K.hairCap = (mat, hd, th, k, ph0, phL) => put('head', mat, new THREE.SphereGeometry(1, 14, 8, ph0 === undefined ? Math.PI : ph0, phL || Math.PI, 0, Math.PI * th), [0, hd.cy, 0], null, [hd.rx * k, hd.ry * k, hd.rz * k]);
  K.headBase = (mat, o) => {
    const p = [];
    for (let i = 0; i <= 14; i++) { const t = i / 14 * Math.PI; p.push([o.rx * Math.sin(t) * (1 + (o.chin || 0) * Math.cos(t)), o.cy - o.ry * Math.cos(t)]); }
    put('head', mat, lathe(p, 20), null, null, [1, 1, o.rz / o.rx]);
    put('head', mat, K.tube(0.06, 0.06, 0.1, 10), [0, 0.03, 0]);
    sym('head', mat, K.blob(0.03, 0.045, 0.025, 8), [o.rx * 0.98, o.cy - 0.01, -0.01]);
  };

  dress(K);
  return finish();
}
