// STORMTILT captain "player", candidate A: assembled primitives (sphere, cylinder, capsule).
// Rig contract: joints torso/head/hat/armL/armR/legL/legR are Groups at the joint (zero rest rotation),
// handL/handR palm markers; all on g.userData.joints. Faces +Z, base at y = 0. Generated by the 404 loop.
export default function (THREE) {
  // ---- PLAYER: young captain, red oilskin, yellow sou'wester, dark trousers, black boots ----
  const D = { H: 1.85, hip: 0.86, legY: 0.84, legX: 0.125, shX: 0.3, shY: 1.28, neck: 1.33, headTop: 1.77, hatTilt: 0.22, splay: 0.15, handY: 0.55 };
  function dress(K) {
    const red = M(0xd7372f, { roughness: 0.22 }), redDk = M(0xa82822, { roughness: 0.3 }), yel = M(0xf2b630, { roughness: 0.25 });
    const navy = M(0x1f2a44, { roughness: 0.6 }), boot = M(0x1b1c20, { roughness: 0.28 }), sole = M(0x0c0c0e, { roughness: 0.6 });
    const skin = M(0xf1c7a0, { roughness: 0.5 }), nose = M(0xeaa27e, { roughness: 0.5 }), hair = M(0x5a3622, { roughness: 0.6 });
    const ink = M(0x15110f, { roughness: 0.2 }), white = M(0xf8f4ea, { roughness: 0.3 });
    const brass = M(0xc9a043, { roughness: 0.3, metalness: 0.7 }), strap = M(0x23262e, { roughness: 0.5 });
    // legs (leg-local, hip joint at 0)
    K.trousers(navy, { y0: 0.02, y1: -0.5, r: 0.108 });
    K.boots(boot, sole, { top: -0.48, r: 0.118, w: 0.12, len: 0.4, toeZ: 0.055, soleH: 0.055 });
    // coat (torso-local, hip pivot at 0)
    K.coat(red, { y0: -0.16, y1: 0.4, rx: 0.265, rz: 0.19, hemR: 0.29, shH: 0.09 });
    put('torso', redDk, new THREE.BoxGeometry(0.035, 0.6, 0.03), [0, 0.1, 0.18]);
    for (const y of [-0.02, 0.12, 0.26]) put('torso', brass, K.tube(0.018, 0.018, 0.075, 8), [0, y, 0.2], [0, 0, Math.PI / 2]);
    sym('torso', redDk, new THREE.BoxGeometry(0.11, 0.035, 0.03), [0.15, -0.04, 0.155], [0, 0.6, 0]);
    put('torso', redDk, new THREE.BoxGeometry(0.03, 0.3, 0.03), [0, -0.06, -0.185]);
    put('torso', redDk, new THREE.BoxGeometry(0.4, 0.03, 0.03), [0, 0.3, -0.17], [-0.3, 0, 0]);
    put('torso', red, new THREE.TorusGeometry(0.105, 0.045, 6, 16), [0, 0.47, -0.005], [Math.PI / 2, 0, 0], [1, 0.9, 1]);
    sym('torso', red, new THREE.BoxGeometry(0.09, 0.1, 0.03), [0.07, 0.42, 0.15], [-0.3, 0, -0.5]);
    // arms (shoulder frame)
    K.sleeves(red, { len: 0.44, r: 0.085, cuffMat: redDk });
    K.hands(skin, { s: 1.35 });
    // head (neck joint at 0)
    const hd = { cy: 0.225, rx: 0.19, ry: 0.215, rz: 0.19, chin: -0.04 };
    K.headBase(skin, hd);
    sym('head', ink, K.blob(0.031, 0.044, 0.018, 10, 8), [0.07, 0.26, 0.163 + K.fz]);
    sym('head', white, K.blob(0.009, 0.009, 0.006, 6, 4), [0.078, 0.277, 0.179 + K.fz]);
    sym('head', hair, K.cap(0.014, 0.06, 6), [0.075, 0.325, 0.153 + K.fz], [0, 0, Math.PI / 2 + 0.18]);
    put('head', nose, K.blob(0.042, 0.048, 0.05, 12, 8), [0, 0.205, 0.193 + K.fz]);
    const teeth = new THREE.SphereGeometry(0.07, 14, 6, 0, Math.PI * 2, Math.PI / 2, Math.PI / 2);
    put('head', white, teeth, [0, 0.14, 0.158 + K.fz], [0.3, 0, 0], [1, 0.6, 0.42]);
    const lip = new THREE.SphereGeometry(0.077, 14, 6, 0, Math.PI * 2, Math.PI / 2, Math.PI / 2);
    put('head', ink, lip, [0, 0.142, 0.153 + K.fz], [0.3, 0, 0], [1, 0.68, 0.42]);
    K.hairCap(hair, hd, 0.62, 1.05);
    sym('head', hair, K.blob(0.028, 0.06, 0.045, 8, 6), [0.175, 0.27, 0.04]);
    put('head', hair, K.blob(0.12, 0.05, 0.07, 10, 6), [0.03, 0.39, 0.1], [0.3, 0, 0.1]);
    put('head', strap, new THREE.TorusGeometry(0.2, 0.01, 4, 16, Math.PI * 1.1), [0, 0.25, 0.04], [0, 0, Math.PI - 0.05 * Math.PI], [1, 1.12, 1]);
    // sou'wester (hat-local, top of the head at 0); back brim longer and lower
    const k = 1.16;
    if (K.style === 'A') {
      putHat(yel, new THREE.SphereGeometry(0.182 * k, 22, 9, 0, Math.PI * 2, 0, Math.PI / 2), [0, -0.03, 0], null, [1, 0.72, 1.04]);
      putHat(yel, K.tube(0.186 * k, 0.182 * k, 0.08, 22), [0, -0.07, 0], null, [1, 1, 1.04]);
      putHat(yel, new THREE.CylinderGeometry(0.185 * k, 0.29 * k, 0.075, 26, 1, true), [0, -0.145, -0.02], [-0.1, 0, 0], [1, 1, 1.06]);
      putHat(yel, new THREE.TorusGeometry(0.29 * k, 0.015, 5, 26), [0, -0.18, -0.025], [Math.PI / 2 - 0.1, 0, 0], [1, 1.06, 1]);
    } else if (K.style === 'B') {
      const p = [[0, 0.1], [0.08, 0.095], [0.145, 0.065], [0.18, 0.005], [0.188, -0.095], [0.215, -0.12], [0.29, -0.165], [0.31, -0.185], [0.3, -0.2], [0.28, -0.19], [0.2, -0.145], [0.172, -0.12]].map(([r, y]) => [r * k, y]);
      putHat(yel, lathe(p, 26), [0, 0, -0.02], [-0.1, 0, 0], [1, 1, 1.05]);
    } else {
      putHat(yel, K.sq(0.185 * k, 0.13, 0.192 * k, 0.85, 0.6, 0.86, 20, 14), [0, -0.03, 0]);
      putHat(yel, K.sq(0.3 * k, 0.022, 0.315 * k, 1, 0.5, 1, 26, 8), [0, -0.145, -0.025], [-0.1, 0, 0]);
    }
  }

  // ---- rig core: identical in every STORMTILT captain ----
  // Joints are Groups placed AT the joint with zero rest rotation; geometry hangs off them,
  // merged per joint per material (one mesh per colour per moving part).
  const V3 = THREE.Vector3;
  const g = new THREE.Group();
  g.name = 'captain';
  const matCache = new Map();
  function M(hex, o) {
    o = o || {};
    const key = hex + '|' + JSON.stringify(o);
    if (!matCache.has(key)) {
      const m = new THREE.MeshStandardMaterial(Object.assign({ color: hex, roughness: 0.32, metalness: 0, side: THREE.DoubleSide }, o));
      matCache.set(key, m);
    }
    return matCache.get(key);
  }
  const W = {}, J = {};
  function joint(name, parent, wx, wy, wz) {
    const o = new THREE.Group();
    o.name = name;
    W[name] = new V3(wx, wy, wz);
    const pw = parent ? W[parent] : new V3();
    o.position.set(wx - pw.x, wy - pw.y, wz - pw.z);
    (parent ? J[parent] : g).add(o);
    J[name] = o;
  }
  joint('torso', null, 0, D.hip, 0);
  joint('head', 'torso', 0, D.neck, 0);
  joint('hat', 'head', 0, D.headTop, 0);
  joint('armL', 'torso', D.shX, D.shY, 0);
  joint('armR', 'torso', -D.shX, D.shY, 0);
  joint('legL', null, D.legX, D.legY, 0);
  joint('legR', null, -D.legX, D.legY, 0);

  const B = new Map();
  const _e = new THREE.Euler(), _q = new THREE.Quaternion();
  function TRS(p, r, s) {
    _e.set(r ? r[0] : 0, r ? r[1] : 0, r ? r[2] : 0);
    _q.setFromEuler(_e);
    return new THREE.Matrix4().compose(new V3(p ? p[0] : 0, p ? p[1] : 0, p ? p[2] : 0), _q.clone(), new V3(s ? s[0] : 1, s ? s[1] : 1, s ? s[2] : 1));
  }
  function add(jn, mat, geo, localM) {
    let q = geo.index ? geo.toNonIndexed() : geo;
    q.deleteAttribute('uv');
    if (!q.attributes.normal) q.computeVertexNormals();
    q.applyMatrix4(localM);
    const k = jn + '|' + mat.uuid;
    if (!B.has(k)) B.set(k, { jn, mat, list: [] });
    B.get(k).list.push(q);
  }
  const mir = (p, sd) => (p ? [p[0] * sd, p[1], p[2]] : null);
  const mirR = (r, sd) => (r ? [r[0], r[1] * sd, r[2] * sd] : null);
  // joint-local placement
  function put(jn, mat, geo, p, r, s) { add(jn, mat, geo, TRS(p, r, s)); }
  // a mirrored pair on one joint (x and -x)
  function sym(jn, mat, geo, p, r, s) { for (const sd of [1, -1]) put(jn, mat, geo.clone(), mir(p, sd), mirR(r, sd), s); }
  // arm frame: origin at the shoulder, the arm hangs along -y, splayed out by D.splay
  function armFrame(sd) { return new THREE.Matrix4().makeRotationZ(sd * D.splay); }
  function putArm(sd, mat, geo, p, r, s) { add(sd > 0 ? 'armL' : 'armR', mat, geo, armFrame(sd).multiply(TRS(mir(p, sd), mirR(r, sd), s))); }
  function arms(mat, geo, p, r, s) { putArm(1, mat, geo.clone(), p, r, s); putArm(-1, mat, geo, p, r, s); }
  // legs: origin at each hip joint
  function putLeg(sd, mat, geo, p, r, s) { put(sd > 0 ? 'legL' : 'legR', mat, geo, mir(p, sd), mirR(r, sd), s); }
  function legs(mat, geo, p, r, s) { putLeg(1, mat, geo.clone(), p, r, s); putLeg(-1, mat, geo, p, r, s); }

  // hat frame: tilted back by D.hatTilt about the top of the head (positive tips the front brim up)
  function putHat(mat, geo, p, r, s) { add('hat', mat, geo, new THREE.Matrix4().makeRotationX(-(D.hatTilt || 0)).multiply(TRS(p, r, s))); }
  function symHat(mat, geo, p, r, s) { for (const sd of [1, -1]) putHat(mat, geo.clone(), mir(p, sd), mirR(r, sd), s); }
  function mergeList(list) {
    let n = 0;
    for (const q of list) n += q.attributes.position.count;
    const P = new Float32Array(n * 3), N = new Float32Array(n * 3);
    let o = 0;
    for (const q of list) { P.set(q.attributes.position.array, o * 3); N.set(q.attributes.normal.array, o * 3); o += q.attributes.position.count; }
    const r = new THREE.BufferGeometry();
    r.setAttribute('position', new THREE.BufferAttribute(P, 3));
    r.setAttribute('normal', new THREE.BufferAttribute(N, 3));
    r.computeBoundingSphere();
    return r;
  }
  function lathe(pts, seg) { return new THREE.LatheGeometry(pts.map((a) => new THREE.Vector2(Math.max(0.0005, a[0]), a[1])), seg || 16); }

  function finish() {
    for (const { jn, mat, list } of B.values()) {
      const m = new THREE.Mesh(mergeList(list), mat);
      m.castShadow = true; m.receiveShadow = true; m.name = jn + '_part';
      J[jn].add(m);
    }
    // palm markers, in the arm frame
    const hands = {};
    for (const sd of [1, -1]) {
      const h = new THREE.Object3D();
      h.name = sd > 0 ? 'handL' : 'handR';
      h.position.set(0, -D.handY, D.handZ || 0).applyMatrix4(armFrame(sd));
      J[sd > 0 ? 'armL' : 'armR'].add(h);
      hands[h.name] = h;
    }
    const measure = () => {
      const box = new THREE.Box3(), v = new V3();
      g.updateMatrixWorld(true);
      g.traverse((n) => {
        const p = n.isMesh && n.geometry.attributes.position; if (!p) return;
        for (let i = 0; i < p.count; i++) box.expandByPoint(v.fromBufferAttribute(p, i).applyMatrix4(n.matrixWorld));
      });
      return box;
    };
    // exact height: every joint has zero rest rotation, so scaling joint offsets and geometry is exact
    let box = measure();
    const k = D.H / (box.max.y - box.min.y);
    g.traverse((n) => { if (n === g) return; n.position.multiplyScalar(k); if (n.isMesh) { n.position.set(0, 0, 0); n.geometry.scale(k, k, k); n.geometry.computeBoundingSphere(); } });
    box = measure();
    const c = box.getCenter(new V3());
    g.children.forEach((o) => { o.position.x -= c.x; o.position.y -= box.min.y; o.position.z -= c.z; });
    g.userData.joints = { torso: J.torso, head: J.head, hat: J.hat, armL: J.armL, armR: J.armR, legL: J.legL, legR: J.legR, handL: hands.handL, handR: hands.handR };
    return g;
  }
  const K = { THREE, D, M, put, sym, putArm, arms, putLeg, legs, putHat, symHat, lathe, TRS, J };

  // ---- body kit A: assembled primitives (sphere, cylinder, capsule) ----
  K.style = 'A';
  K.fz = 0;
  K.blob = (rx, ry, rz, ws, hs) => { const s = new THREE.SphereGeometry(1, ws || 12, hs || 9); s.scale(rx, ry, rz); return s; };
  K.tube = (rBot, rTop, h, seg) => new THREE.CylinderGeometry(rTop, rBot, h, seg || 14);
  K.cap = (r, len, seg) => new THREE.CapsuleGeometry(r, len, 3, seg || 8);
  K.trousers = (mat, o) => {
    legs(mat, K.tube(o.r * (o.taper || 0.92), o.r, o.y0 - o.y1), [0, (o.y0 + o.y1) / 2, 0]);
    legs(mat, K.blob(o.r * 0.95, o.r * 0.6, o.r * 0.95, 12, 8), [0, o.y1, 0]);
  };
  K.boots = (mat, sole, o) => {
    const b = -D.legY, sh = o.soleH || 0.05;
    legs(mat, K.tube(o.r * 1.04, o.r, o.top - (b + 0.1)), [0, (o.top + b + 0.1) / 2, 0]);
    legs(mat, K.blob(o.w, 0.1, o.len / 2), [0, b + sh + 0.04, o.toeZ]);
    legs(sole, K.tube(1, 1, sh, 16), [0, b + sh / 2, o.toeZ], null, [o.w * 1.06, 1, (o.len / 2) * 1.04]);
    if (o.cuffMat) legs(o.cuffMat, K.tube(o.r * 1.12, o.r * 1.14, 0.06), [0, o.top - 0.02, 0]);
  };
  K.coat = (mat, o) => {
    const h = o.y1 - o.y0, sz = o.rz / o.rx;
    put('torso', mat, K.tube(o.hemR, o.rx, h, 20), [0, o.y0 + h / 2, 0], null, [1, 1, sz]);
    put('torso', mat, new THREE.SphereGeometry(o.rx, 20, 7, 0, Math.PI * 2, 0, Math.PI / 2), [0, o.y1, 0], null, [1, (o.shH || 0.1) / o.rx, sz]);
    if (o.belly) put('torso', mat, K.blob(o.rx * 1.02, h * 0.42, o.rz * 1.18, 18, 12), [0, o.y0 + h * 0.45, 0.02]);
  };
  K.sleeves = (mat, o) => {
    arms(mat, K.cap(o.r, o.len - o.r, 12), [0, -o.len / 2 + 0.02, 0]);
    if (o.cuffMat) arms(o.cuffMat, K.tube(o.r * 1.12, o.r * 1.12, 0.05, 12), [0, -o.len + 0.03, 0]);
  };
  K.hands = (mat, o) => {
    const y = -D.handY, s = o.s || 1;
    arms(mat, K.blob(0.042 * s, 0.07 * s, 0.07 * s, 10, 8), [0, y + 0.02 * s, 0]);
    for (let i = 0; i < 3; i++) arms(mat, K.blob(0.02 * s, 0.045 * s, 0.02 * s, 8, 6), [0.004, y - 0.06 * s, (0.04 - i * 0.038) * s], [0, 0, 0.12]);
    arms(mat, K.blob(0.021 * s, 0.045 * s, 0.021 * s, 8, 6), [-0.025 * s, y + 0.0, 0.07 * s], [0.6, 0, -0.5]);
  };
  K.hairCap = (mat, hd, th, k, ph0, phL) => put('head', mat, new THREE.SphereGeometry(1, 14, 8, ph0 === undefined ? Math.PI : ph0, phL || Math.PI, 0, Math.PI * th), [0, hd.cy, 0], null, [hd.rx * k, hd.ry * k, hd.rz * k]);
  K.headBase = (mat, o) => {
    put('head', mat, K.blob(o.rx, o.ry, o.rz, 18, 13), [0, o.cy, 0]);
    put('head', mat, K.tube(0.06, 0.06, 0.1, 10), [0, 0.03, 0]);
    sym('head', mat, K.blob(0.03, 0.045, 0.025, 8, 6), [o.rx * 0.98, o.cy - 0.01, -0.01]);
  };

  dress(K);
  return finish();
}
