// STORMTILT captain "volta", candidate A: assembled primitives (sphere, cylinder, capsule).
// Rig contract: joints torso/head/hat/armL/armR/legL/legR are Groups at the joint (zero rest rotation),
// handL/handR palm markers; all on g.userData.joints. Faces +Z, base at y = 0. Generated by the 404 loop.
export default function (THREE) {
  // ---- DOC VOLTA: white lab coat over green waders, copper goggles on the forehead, wild white hair, copper coil backpack ----
  const D = { H: 1.85, hip: 0.9, legY: 0.88, legX: 0.12, shX: 0.3, shY: 1.33, neck: 1.38, headTop: 1.8, hatTilt: 0, splay: 0.17, handY: 0.55 };
  function dress(K) {
    const coat = M(0xe9e6dc, { roughness: 0.6 }), coatDk = M(0xc9c5b8, { roughness: 0.7 }), green = M(0x5f7a45, { roughness: 0.45 });
    const olive = M(0x6b6a45, { roughness: 0.45 }), oliveDk = M(0x3e3d28, { roughness: 0.6 }), rope = M(0xb59a6a, { roughness: 0.8 });
    const copper = M(0xc46a3a, { roughness: 0.3, metalness: 0.75 }), glass = M(0x1c2a30, { roughness: 0.1, metalness: 0.3 });
    const strapM = M(0x3a3d42, { roughness: 0.6 }), spark = M(0x9fe8ff, { roughness: 0.3, emissive: 0x9fe8ff, emissiveIntensity: 1.4 });
    const skin = M(0xf1c7a0, { roughness: 0.5 }), nose = M(0xe9a582, { roughness: 0.5 }), hairW = M(0xeceae4, { roughness: 0.55 });
    const ink = M(0x15110f, { roughness: 0.2 }), white = M(0xfbf8f0, { roughness: 0.3 });
    // waders and boots
    K.trousers(green, { y0: 0.02, y1: -0.5, r: 0.108 });
    K.boots(olive, oliveDk, { top: -0.5, r: 0.12, w: 0.125, len: 0.4, toeZ: 0.055, soleH: 0.055, cuffMat: olive });
    // long open lab coat: white body, green bib showing down the open front
    K.coat(coat, { y0: -0.36, y1: 0.38, rx: 0.25, rz: 0.18, hemR: 0.29, shH: 0.09 });
    put('torso', green, K.blob(0.15, 0.42, 0.05, 10, 8), [0, -0.02, 0.165]);
    sym('torso', coatDk, new THREE.BoxGeometry(0.035, 0.72, 0.03), [0.15, 0.0, 0.175], [0, 0.4, -0.03]);
    sym('torso', coat, new THREE.BoxGeometry(0.08, 0.16, 0.025), [0.1, 0.34, 0.15], [-0.35, 0.3, -0.35]);
    sym('torso', coatDk, new THREE.BoxGeometry(0.1, 0.11, 0.02), [0.17, -0.12, 0.15], [0, 0.65, 0]);
    put('torso', coatDk, new THREE.BoxGeometry(0.03, 0.34, 0.03), [0, -0.2, -0.205]);
    put('torso', rope, new THREE.TorusGeometry(0.2, 0.017, 5, 16, Math.PI * 0.55), [0, 0.0, 0.0], [Math.PI / 2, 0, Math.PI * 0.225], [1, 0.95, 1]);
    put('torso', rope, K.cap(0.016, 0.16, 5), [0.03, -0.1, 0.205], [0.1, 0, 0.12]);
    // backpack straps and the copper coil backpack
    sym('torso', strapM, new THREE.BoxGeometry(0.04, 0.03, 0.4), [0.15, 0.4, -0.02], [0, 0, 0.35]);
    put('torso', copper, K.tube(0.11, 0.11, 0.3, 14), [0, 0.2, -0.3]);
    put('torso', copper, K.blob(0.11, 0.06, 0.11, 12, 6), [0, 0.35, -0.3]);
    put('torso', copper, K.blob(0.11, 0.05, 0.11, 12, 6), [0, 0.05, -0.3]);
    for (const y of [0.12, 0.28]) put('torso', strapM, new THREE.TorusGeometry(0.112, 0.012, 4, 16), [0, y, -0.3], [Math.PI / 2, 0, 0]);
    const helix = [];
    for (let i = 0; i <= 64; i++) { const t = i / 64, a = t * Math.PI * 2 * 6; helix.push(new THREE.Vector3(-0.07 + Math.cos(a) * 0.05, 0.38 + t * 0.24, -0.3 + Math.sin(a) * 0.05)); }
    put('torso', copper, new THREE.TubeGeometry(new THREE.CatmullRomCurve3(helix), 56, 0.01, 3));
    put('torso', copper, K.tube(0.012, 0.012, 0.3, 6), [-0.07, 0.5, -0.3]);
    put('torso', spark, K.blob(0.03, 0.05, 0.03, 8, 6), [-0.07, 0.67, -0.3]);
    sym('torso', spark, new THREE.TorusGeometry(0.1, 0.012, 4, 12, Math.PI * 0.8), [0.11, 0.18, -0.26], [0, Math.PI / 2, 0]);
    // arms
    K.sleeves(coat, { len: 0.44, r: 0.085, cuffMat: coatDk });
    K.hands(skin, { s: 1.3 });
    // head: big grin, bushy white brows
    const hd = { cy: 0.21, rx: 0.17, ry: 0.21, rz: 0.175, chin: -0.06 };
    K.headBase(skin, hd);
    sym('head', ink, K.blob(0.028, 0.04, 0.016, 8, 6), [0.064, 0.24, 0.15 + K.fz]);
    sym('head', white, K.blob(0.008, 0.008, 0.006, 5, 4), [0.071, 0.256, 0.165 + K.fz]);
    sym('head', hairW, K.blob(0.05, 0.022, 0.03, 8, 6), [0.07, 0.29, 0.14 + K.fz], [0, 0, -0.35]);
    put('head', nose, K.blob(0.035, 0.05, 0.048, 12, 8), [0, 0.195, 0.18 + K.fz]);
    const teeth = new THREE.SphereGeometry(0.068, 14, 6, 0, Math.PI * 2, Math.PI / 2, Math.PI / 2);
    put('head', white, teeth, [0, 0.125, 0.14 + K.fz], [0.3, 0, 0], [1, 0.6, 0.42]);
    const lip = new THREE.SphereGeometry(0.074, 14, 6, 0, Math.PI * 2, Math.PI / 2, Math.PI / 2);
    put('head', ink, lip, [0, 0.127, 0.135 + K.fz], [0.3, 0, 0], [1, 0.68, 0.42]);
    // wild hair: a cap over the back and spikes flung up and back
    K.hairCap(hairW, hd, 0.7, 1.06);
    const up = new THREE.Vector3(0, 1, 0);
    const tufts = [[0.9, 0.55], [-0.9, 0.55], [1.5, 0.35], [-1.5, 0.35], [2.1, 0.45], [-2.1, 0.45], [Math.PI, 0.5], [2.6, 0.1], [-2.6, 0.1], [1.8, -0.05], [-1.8, -0.05], [0.45, 0.95], [-0.45, 0.95], [Math.PI, 0.05], [1.2, 1.1], [-1.2, 1.1], [2.5, 0.85], [-2.5, 0.85]];
    for (const [th, ph] of tufts) {
      const n = new THREE.Vector3(Math.sin(th) * Math.cos(ph), Math.sin(ph), Math.cos(th) * Math.cos(ph));
      const base = new THREE.Vector3(n.x * hd.rx, hd.cy + n.y * hd.ry, n.z * hd.rz).multiplyScalar(0.96).add(new THREE.Vector3(0, hd.cy * 0.04, 0));
      const dir = n.clone().add(new THREE.Vector3(0, 0.25, -0.55)).normalize();
      const len = 0.15 + 0.05 * Math.cos(th * 3) + 0.03 * ph;
      const e = new THREE.Euler().setFromQuaternion(new THREE.Quaternion().setFromUnitVectors(up, dir));
      put('head', hairW, new THREE.ConeGeometry(0.06, len, 6, 1), base.addScaledVector(dir, len * 0.42).toArray(), [e.x, e.y, e.z], [1, 1, 0.6]);
    }
    sym('head', hairW, K.blob(0.05, 0.07, 0.07, 8, 6), [0.16, 0.25, -0.02]);
    // goggles on the forehead (the 'hat' joint: they can fly off)
    putHat(copper, new THREE.TorusGeometry(1, 0.012, 4, 22), [0, -0.07, -0.005], [Math.PI / 2 + 0.25, 0, 0], [0.178, 0.188, 1]);
    for (const sd of [1, -1]) {
      const p = [0.065 * sd, -0.05, 0.14];
      if (K.style === 'B') putHat(copper, lathe([[0.045, -0.035], [0.052, -0.03], [0.05, 0.02], [0.056, 0.03], [0.04, 0.035]], 14), p, [Math.PI / 2 - 0.5, 0, 0]);
      else if (K.style === 'C') putHat(copper, K.sq(0.052, 0.035, 0.052, 1, 0.4, 0.9, 14, 6), p, [Math.PI / 2 - 0.5, 0, 0]);
      else putHat(copper, K.tube(0.05, 0.054, 0.065, 14), p, [Math.PI / 2 - 0.5, 0, 0]);
      putHat(glass, new THREE.CircleGeometry(0.04, 14), [p[0], p[1] + 0.017, p[2] + 0.03], [-0.5, 0, 0]);
      putHat(copper, new THREE.TorusGeometry(0.046, 0.009, 4, 14), [p[0], p[1] + 0.018, p[2] + 0.031], [-0.5, 0, 0]);
    }
    putHat(copper, K.tube(0.012, 0.012, 0.03, 6), [0, -0.04, 0.155], [0, 0, Math.PI / 2]);
  }

  // ---- rig core: identical in every STORMTILT captain ----
  // Joints are Groups placed AT the joint with zero rest rotation; geometry hangs off them,
  // merged per joint per material (one mesh per colour per moving part).
  const V3 = THREE.Vector3;
  const g = new THREE.Group();
  g.name = 'captain';
  const matCache = new Map();
  function M(hex, o) {
    o = o || {};
    const key = hex + '|' + JSON.stringify(o);
    if (!matCache.has(key)) {
      const m = new THREE.MeshStandardMaterial(Object.assign({ color: hex, roughness: 0.32, metalness: 0, side: THREE.DoubleSide }, o));
      matCache.set(key, m);
    }
    return matCache.get(key);
  }
  const W = {}, J = {};
  function joint(name, parent, wx, wy, wz) {
    const o = new THREE.Group();
    o.name = name;
    W[name] = new V3(wx, wy, wz);
    const pw = parent ? W[parent] : new V3();
    o.position.set(wx - pw.x, wy - pw.y, wz - pw.z);
    (parent ? J[parent] : g).add(o);
    J[name] = o;
  }
  joint('torso', null, 0, D.hip, 0);
  joint('head', 'torso', 0, D.neck, 0);
  joint('hat', 'head', 0, D.headTop, 0);
  joint('armL', 'torso', D.shX, D.shY, 0);
  joint('armR', 'torso', -D.shX, D.shY, 0);
  joint('legL', null, D.legX, D.legY, 0);
  joint('legR', null, -D.legX, D.legY, 0);

  const B = new Map();
  const _e = new THREE.Euler(), _q = new THREE.Quaternion();
  function TRS(p, r, s) {
    _e.set(r ? r[0] : 0, r ? r[1] : 0, r ? r[2] : 0);
    _q.setFromEuler(_e);
    return new THREE.Matrix4().compose(new V3(p ? p[0] : 0, p ? p[1] : 0, p ? p[2] : 0), _q.clone(), new V3(s ? s[0] : 1, s ? s[1] : 1, s ? s[2] : 1));
  }
  function add(jn, mat, geo, localM) {
    let q = geo.index ? geo.toNonIndexed() : geo;
    q.deleteAttribute('uv');
    if (!q.attributes.normal) q.computeVertexNormals();
    q.applyMatrix4(localM);
    const k = jn + '|' + mat.uuid;
    if (!B.has(k)) B.set(k, { jn, mat, list: [] });
    B.get(k).list.push(q);
  }
  const mir = (p, sd) => (p ? [p[0] * sd, p[1], p[2]] : null);
  const mirR = (r, sd) => (r ? [r[0], r[1] * sd, r[2] * sd] : null);
  // joint-local placement
  function put(jn, mat, geo, p, r, s) { add(jn, mat, geo, TRS(p, r, s)); }
  // a mirrored pair on one joint (x and -x)
  function sym(jn, mat, geo, p, r, s) { for (const sd of [1, -1]) put(jn, mat, geo.clone(), mir(p, sd), mirR(r, sd), s); }
  // arm frame: origin at the shoulder, the arm hangs along -y, splayed out by D.splay
  function armFrame(sd) { return new THREE.Matrix4().makeRotationZ(sd * D.splay); }
  function putArm(sd, mat, geo, p, r, s) { add(sd > 0 ? 'armL' : 'armR', mat, geo, armFrame(sd).multiply(TRS(mir(p, sd), mirR(r, sd), s))); }
  function arms(mat, geo, p, r, s) { putArm(1, mat, geo.clone(), p, r, s); putArm(-1, mat, geo, p, r, s); }
  // legs: origin at each hip joint
  function putLeg(sd, mat, geo, p, r, s) { put(sd > 0 ? 'legL' : 'legR', mat, geo, mir(p, sd), mirR(r, sd), s); }
  function legs(mat, geo, p, r, s) { putLeg(1, mat, geo.clone(), p, r, s); putLeg(-1, mat, geo, p, r, s); }

  // hat frame: tilted back by D.hatTilt about the top of the head (positive tips the front brim up)
  function putHat(mat, geo, p, r, s) { add('hat', mat, geo, new THREE.Matrix4().makeRotationX(-(D.hatTilt || 0)).multiply(TRS(p, r, s))); }
  function symHat(mat, geo, p, r, s) { for (const sd of [1, -1]) putHat(mat, geo.clone(), mir(p, sd), mirR(r, sd), s); }
  function mergeList(list) {
    let n = 0;
    for (const q of list) n += q.attributes.position.count;
    const P = new Float32Array(n * 3), N = new Float32Array(n * 3);
    let o = 0;
    for (const q of list) { P.set(q.attributes.position.array, o * 3); N.set(q.attributes.normal.array, o * 3); o += q.attributes.position.count; }
    const r = new THREE.BufferGeometry();
    r.setAttribute('position', new THREE.BufferAttribute(P, 3));
    r.setAttribute('normal', new THREE.BufferAttribute(N, 3));
    r.computeBoundingSphere();
    return r;
  }
  function lathe(pts, seg) { return new THREE.LatheGeometry(pts.map((a) => new THREE.Vector2(Math.max(0.0005, a[0]), a[1])), seg || 16); }

  function finish() {
    for (const { jn, mat, list } of B.values()) {
      const m = new THREE.Mesh(mergeList(list), mat);
      m.castShadow = true; m.receiveShadow = true; m.name = jn + '_part';
      J[jn].add(m);
    }
    // palm markers, in the arm frame
    const hands = {};
    for (const sd of [1, -1]) {
      const h = new THREE.Object3D();
      h.name = sd > 0 ? 'handL' : 'handR';
      h.position.set(0, -D.handY, D.handZ || 0).applyMatrix4(armFrame(sd));
      J[sd > 0 ? 'armL' : 'armR'].add(h);
      hands[h.name] = h;
    }
    const measure = () => {
      const box = new THREE.Box3(), v = new V3();
      g.updateMatrixWorld(true);
      g.traverse((n) => {
        const p = n.isMesh && n.geometry.attributes.position; if (!p) return;
        for (let i = 0; i < p.count; i++) box.expandByPoint(v.fromBufferAttribute(p, i).applyMatrix4(n.matrixWorld));
      });
      return box;
    };
    // exact height: every joint has zero rest rotation, so scaling joint offsets and geometry is exact
    let box = measure();
    const k = D.H / (box.max.y - box.min.y);
    g.traverse((n) => { if (n === g) return; n.position.multiplyScalar(k); if (n.isMesh) { n.position.set(0, 0, 0); n.geometry.scale(k, k, k); n.geometry.computeBoundingSphere(); } });
    box = measure();
    const c = box.getCenter(new V3());
    g.children.forEach((o) => { o.position.x -= c.x; o.position.y -= box.min.y; o.position.z -= c.z; });
    g.userData.joints = { torso: J.torso, head: J.head, hat: J.hat, armL: J.armL, armR: J.armR, legL: J.legL, legR: J.legR, handL: hands.handL, handR: hands.handR };
    return g;
  }
  const K = { THREE, D, M, put, sym, putArm, arms, putLeg, legs, putHat, symHat, lathe, TRS, J };

  // ---- body kit A: assembled primitives (sphere, cylinder, capsule) ----
  K.style = 'A';
  K.fz = 0;
  K.blob = (rx, ry, rz, ws, hs) => { const s = new THREE.SphereGeometry(1, ws || 12, hs || 9); s.scale(rx, ry, rz); return s; };
  K.tube = (rBot, rTop, h, seg) => new THREE.CylinderGeometry(rTop, rBot, h, seg || 14);
  K.cap = (r, len, seg) => new THREE.CapsuleGeometry(r, len, 3, seg || 8);
  K.trousers = (mat, o) => {
    legs(mat, K.tube(o.r * (o.taper || 0.92), o.r, o.y0 - o.y1), [0, (o.y0 + o.y1) / 2, 0]);
    legs(mat, K.blob(o.r * 0.95, o.r * 0.6, o.r * 0.95, 12, 8), [0, o.y1, 0]);
  };
  K.boots = (mat, sole, o) => {
    const b = -D.legY, sh = o.soleH || 0.05;
    legs(mat, K.tube(o.r * 1.04, o.r, o.top - (b + 0.1)), [0, (o.top + b + 0.1) / 2, 0]);
    legs(mat, K.blob(o.w, 0.1, o.len / 2), [0, b + sh + 0.04, o.toeZ]);
    legs(sole, K.tube(1, 1, sh, 16), [0, b + sh / 2, o.toeZ], null, [o.w * 1.06, 1, (o.len / 2) * 1.04]);
    if (o.cuffMat) legs(o.cuffMat, K.tube(o.r * 1.12, o.r * 1.14, 0.06), [0, o.top - 0.02, 0]);
  };
  K.coat = (mat, o) => {
    const h = o.y1 - o.y0, sz = o.rz / o.rx;
    put('torso', mat, K.tube(o.hemR, o.rx, h, 20), [0, o.y0 + h / 2, 0], null, [1, 1, sz]);
    put('torso', mat, new THREE.SphereGeometry(o.rx, 20, 7, 0, Math.PI * 2, 0, Math.PI / 2), [0, o.y1, 0], null, [1, (o.shH || 0.1) / o.rx, sz]);
    if (o.belly) put('torso', mat, K.blob(o.rx * 1.02, h * 0.42, o.rz * 1.18, 18, 12), [0, o.y0 + h * 0.45, 0.02]);
  };
  K.sleeves = (mat, o) => {
    arms(mat, K.cap(o.r, o.len - o.r, 12), [0, -o.len / 2 + 0.02, 0]);
    if (o.cuffMat) arms(o.cuffMat, K.tube(o.r * 1.12, o.r * 1.12, 0.05, 12), [0, -o.len + 0.03, 0]);
  };
  K.hands = (mat, o) => {
    const y = -D.handY, s = o.s || 1;
    arms(mat, K.blob(0.042 * s, 0.07 * s, 0.07 * s, 10, 8), [0, y + 0.02 * s, 0]);
    for (let i = 0; i < 3; i++) arms(mat, K.blob(0.02 * s, 0.045 * s, 0.02 * s, 8, 6), [0.004, y - 0.06 * s, (0.04 - i * 0.038) * s], [0, 0, 0.12]);
    arms(mat, K.blob(0.021 * s, 0.045 * s, 0.021 * s, 8, 6), [-0.025 * s, y + 0.0, 0.07 * s], [0.6, 0, -0.5]);
  };
  K.hairCap = (mat, hd, th, k, ph0, phL) => put('head', mat, new THREE.SphereGeometry(1, 14, 8, ph0 === undefined ? Math.PI : ph0, phL || Math.PI, 0, Math.PI * th), [0, hd.cy, 0], null, [hd.rx * k, hd.ry * k, hd.rz * k]);
  K.headBase = (mat, o) => {
    put('head', mat, K.blob(o.rx, o.ry, o.rz, 18, 13), [0, o.cy, 0]);
    put('head', mat, K.tube(0.06, 0.06, 0.1, 10), [0, 0.03, 0]);
    sym('head', mat, K.blob(0.03, 0.045, 0.025, 8, 6), [o.rx * 0.98, o.cy - 0.01, -0.01]);
  };

  dress(K);
  return finish();
}
