// Assembles self-contained captain candidates: captain spec + rig core + one body kit.
// usage: node build.mjs <id>   -> cand/<id>/<id>_A.js, _B.js, _C.js
import fs from 'fs';
import path from 'path';
const HERE = path.dirname(new URL(import.meta.url).pathname);
const id = process.argv[2];
const src = (f) => fs.readFileSync(path.join(HERE, 'src', f), 'utf8');
const names = { A: 'assembled primitives (sphere, cylinder, capsule)', B: 'lathe profiles', C: 'superellipsoid vinyl blocks' };
const outDir = path.join(HERE, 'cand', id);
fs.mkdirSync(outDir, { recursive: true });
for (const s of ['A', 'B', 'C']) {
  const body = `// STORMTILT captain "${id}", candidate ${s}: ${names[s]}.
// Rig contract: joints torso/head/hat/armL/armR/legL/legR are Groups at the joint (zero rest rotation),
// handL/handR palm markers; all on g.userData.joints. Faces +Z, base at y = 0. Generated by the 404 loop.
export default function (THREE) {
${src('cap_' + id + '.js')}
${src('core.js')}
${src('body' + s + '.js')}
  dress(K);
  return finish();
}
`;
  fs.writeFileSync(path.join(outDir, `${id}_${s}.js`), body);
  const H = { pip: 1.55 }[id] || 1.85;
  fs.writeFileSync(path.join(outDir, `${id}_${s}.expect.json`), JSON.stringify({ height: H, tolerance: 0.1 }) + '\n');
}
console.log('built', id);
