// STORMTILT captain "pip", candidate C: superellipsoid vinyl blocks.
// Rig contract: joints torso/head/hat/armL/armR/legL/legR are Groups at the joint (zero rest rotation),
// handL/handR palm markers; all on g.userData.joints. Faces +Z, base at y = 0. Generated by the 404 loop.
export default function (THREE) {
  // ---- PIP TILLER: small rookie, orange life vest over a white shirt, white sailor cap with a navy band, yellow boots ----
  const D = { H: 1.55, hip: 0.72, legY: 0.7, legX: 0.115, shX: 0.27, shY: 1.1, neck: 1.15, headTop: 1.62, hatTilt: 0.14, splay: 0.2, handY: 0.45 };
  function dress(K) {
    const orange = M(0xf0812a, { roughness: 0.3 }), orangeDk = M(0xc8611c, { roughness: 0.4 }), tan = M(0xb98a52, { roughness: 0.5 });
    const white = M(0xf3eee3, { roughness: 0.4 }), navy = M(0x1f2a55, { roughness: 0.45 }), khaki = M(0xcdb68c, { roughness: 0.7 });
    const yel = M(0xf2b630, { roughness: 0.25 }), yelDk = M(0xc98f1c, { roughness: 0.5 });
    const skin = M(0xf1c7a0, { roughness: 0.5 }), nose = M(0xeda07c, { roughness: 0.5 }), hair = M(0x5b3a22, { roughness: 0.6 });
    const ink = M(0x15110f, { roughness: 0.2 }), brass = M(0xc9a043, { roughness: 0.3, metalness: 0.7 });
    // legs: shorts, bare shins, rubber boots
    K.trousers(khaki, { y0: 0.02, y1: -0.22, r: 0.115, taper: 1.0 });
    K.trousers(skin, { y0: -0.12, y1: -0.46, r: 0.062 });
    K.boots(yel, yelDk, { top: -0.4, r: 0.1, w: 0.112, len: 0.34, toeZ: 0.05, soleH: 0.05, cuffMat: yel });
    // life vest over the torso
    K.coat(orange, { y0: -0.1, y1: 0.33, rx: 0.255, rz: 0.2, hemR: 0.25, shH: 0.1 });
    sym('torso', orange, K.blob(0.11, 0.17, 0.07, 10, 8), [0.1, 0.17, 0.15]);
    put('torso', orange, K.blob(0.2, 0.17, 0.07, 10, 8), [0, 0.15, -0.16]);
    put('torso', orangeDk, new THREE.BoxGeometry(0.02, 0.36, 0.03), [0, 0.1, 0.205]);
    put('torso', orange, new THREE.TorusGeometry(0.12, 0.055, 6, 14), [0, 0.39, -0.01], [Math.PI / 2 - 0.15, 0, 0], [1, 0.95, 1]);
    put('torso', white, K.blob(0.07, 0.06, 0.04), [0, 0.37, 0.12]);
    put('torso', tan, K.tube(0.27, 0.27, 0.06, 20), [0, 0.0, 0], null, [1, 1, 0.82]);
    put('torso', tan, new THREE.BoxGeometry(0.11, 0.07, 0.04), [0, 0.0, 0.225]);
    put('torso', brass, new THREE.BoxGeometry(0.05, 0.03, 0.02), [0, 0.0, 0.25]);
    // arms: white short sleeve with a navy band over a bare arm
    K.sleeves(skin, { len: 0.36, r: 0.052 });
    K.sleeves(white, { len: 0.17, r: 0.078, cuffMat: navy });
    K.hands(skin, { s: 1.3 });
    // big head, worried face
    const hd = { cy: 0.25, rx: 0.2, ry: 0.23, rz: 0.2, chin: -0.02 };
    K.headBase(skin, hd);
    sym('head', ink, K.blob(0.03, 0.045, 0.018, 8, 6), [0.072, 0.27, 0.172 + K.fz]);
    sym('head', white, K.blob(0.009, 0.009, 0.006, 5, 4), [0.08, 0.288, 0.188 + K.fz]);
    sym('head', hair, K.cap(0.013, 0.055, 6), [0.075, 0.345, 0.16 + K.fz], [0, 0, Math.PI / 2 - 0.4]);
    put('head', nose, K.blob(0.04, 0.046, 0.05, 12, 8), [0, 0.215, 0.205 + K.fz]);
    put('head', ink, K.blob(0.034, 0.013, 0.012, 10, 6), [0, 0.13, 0.178 + K.fz], [0, 0, 0.08]);
    put('head', M(0xe9a8a0, { roughness: 0.5 }), K.blob(0.036, 0.02, 0.01, 8, 6), [0, 0.12, 0.172 + K.fz]);
    K.hairCap(hair, hd, 0.6, 1.05);
    sym('head', hair, K.blob(0.024, 0.055, 0.035, 8, 6), [0.175, 0.31, 0.1]);
    // sailor cap (hat-local, top of the head at 0)
    const k = 1.1;
    if (K.style === 'A') {
      putHat(navy, K.tube(0.215 * k, 0.215 * k, 0.075, 22), [0, -0.075, 0]);
      putHat(white, new THREE.SphereGeometry(0.235 * k, 22, 8, 0, Math.PI * 2, 0, Math.PI / 2), [0, -0.035, 0], null, [1, 0.5, 1]);
      putHat(white, new THREE.TorusGeometry(0.235 * k, 0.03, 6, 26), [0, -0.035, 0], [Math.PI / 2, 0, 0]);
    } else if (K.style === 'B') {
      const p = [[0.205, -0.115], [0.218, -0.11], [0.22, -0.04], [0.245, -0.035], [0.26, -0.02], [0.255, 0.0], [0.23, 0.04], [0.17, 0.08], [0.09, 0.1], [0, 0.105]].map(([r, y]) => [r * k, y]);
      putHat(white, lathe(p.slice(2), 24));
      putHat(navy, lathe([[0.205 * k, -0.115], [0.222 * k, -0.11], [0.222 * k, -0.035], [0.2 * k, -0.03]], 24));
    } else {
      putHat(navy, K.sq(0.218 * k, 0.04, 0.218 * k, 1, 0.35, 1, 22, 8), [0, -0.075, 0]);
      putHat(white, K.sq(0.245 * k, 0.07, 0.245 * k, 0.95, 0.7, 0.85, 22, 10), [0, 0.0, 0]);
    }
  }

  // ---- rig core: identical in every STORMTILT captain ----
  // Joints are Groups placed AT the joint with zero rest rotation; geometry hangs off them,
  // merged per joint per material (one mesh per colour per moving part).
  const V3 = THREE.Vector3;
  const g = new THREE.Group();
  g.name = 'captain';
  const matCache = new Map();
  function M(hex, o) {
    o = o || {};
    const key = hex + '|' + JSON.stringify(o);
    if (!matCache.has(key)) {
      const m = new THREE.MeshStandardMaterial(Object.assign({ color: hex, roughness: 0.32, metalness: 0, side: THREE.DoubleSide }, o));
      matCache.set(key, m);
    }
    return matCache.get(key);
  }
  const W = {}, J = {};
  function joint(name, parent, wx, wy, wz) {
    const o = new THREE.Group();
    o.name = name;
    W[name] = new V3(wx, wy, wz);
    const pw = parent ? W[parent] : new V3();
    o.position.set(wx - pw.x, wy - pw.y, wz - pw.z);
    (parent ? J[parent] : g).add(o);
    J[name] = o;
  }
  joint('torso', null, 0, D.hip, 0);
  joint('head', 'torso', 0, D.neck, 0);
  joint('hat', 'head', 0, D.headTop, 0);
  joint('armL', 'torso', D.shX, D.shY, 0);
  joint('armR', 'torso', -D.shX, D.shY, 0);
  joint('legL', null, D.legX, D.legY, 0);
  joint('legR', null, -D.legX, D.legY, 0);

  const B = new Map();
  const _e = new THREE.Euler(), _q = new THREE.Quaternion();
  function TRS(p, r, s) {
    _e.set(r ? r[0] : 0, r ? r[1] : 0, r ? r[2] : 0);
    _q.setFromEuler(_e);
    return new THREE.Matrix4().compose(new V3(p ? p[0] : 0, p ? p[1] : 0, p ? p[2] : 0), _q.clone(), new V3(s ? s[0] : 1, s ? s[1] : 1, s ? s[2] : 1));
  }
  function add(jn, mat, geo, localM) {
    let q = geo.index ? geo.toNonIndexed() : geo;
    q.deleteAttribute('uv');
    if (!q.attributes.normal) q.computeVertexNormals();
    q.applyMatrix4(localM);
    const k = jn + '|' + mat.uuid;
    if (!B.has(k)) B.set(k, { jn, mat, list: [] });
    B.get(k).list.push(q);
  }
  const mir = (p, sd) => (p ? [p[0] * sd, p[1], p[2]] : null);
  const mirR = (r, sd) => (r ? [r[0], r[1] * sd, r[2] * sd] : null);
  // joint-local placement
  function put(jn, mat, geo, p, r, s) { add(jn, mat, geo, TRS(p, r, s)); }
  // a mirrored pair on one joint (x and -x)
  function sym(jn, mat, geo, p, r, s) { for (const sd of [1, -1]) put(jn, mat, geo.clone(), mir(p, sd), mirR(r, sd), s); }
  // arm frame: origin at the shoulder, the arm hangs along -y, splayed out by D.splay
  function armFrame(sd) { return new THREE.Matrix4().makeRotationZ(sd * D.splay); }
  function putArm(sd, mat, geo, p, r, s) { add(sd > 0 ? 'armL' : 'armR', mat, geo, armFrame(sd).multiply(TRS(mir(p, sd), mirR(r, sd), s))); }
  function arms(mat, geo, p, r, s) { putArm(1, mat, geo.clone(), p, r, s); putArm(-1, mat, geo, p, r, s); }
  // legs: origin at each hip joint
  function putLeg(sd, mat, geo, p, r, s) { put(sd > 0 ? 'legL' : 'legR', mat, geo, mir(p, sd), mirR(r, sd), s); }
  function legs(mat, geo, p, r, s) { putLeg(1, mat, geo.clone(), p, r, s); putLeg(-1, mat, geo, p, r, s); }

  // hat frame: tilted back by D.hatTilt about the top of the head (positive tips the front brim up)
  function putHat(mat, geo, p, r, s) { add('hat', mat, geo, new THREE.Matrix4().makeRotationX(-(D.hatTilt || 0)).multiply(TRS(p, r, s))); }
  function symHat(mat, geo, p, r, s) { for (const sd of [1, -1]) putHat(mat, geo.clone(), mir(p, sd), mirR(r, sd), s); }
  function mergeList(list) {
    let n = 0;
    for (const q of list) n += q.attributes.position.count;
    const P = new Float32Array(n * 3), N = new Float32Array(n * 3);
    let o = 0;
    for (const q of list) { P.set(q.attributes.position.array, o * 3); N.set(q.attributes.normal.array, o * 3); o += q.attributes.position.count; }
    const r = new THREE.BufferGeometry();
    r.setAttribute('position', new THREE.BufferAttribute(P, 3));
    r.setAttribute('normal', new THREE.BufferAttribute(N, 3));
    r.computeBoundingSphere();
    return r;
  }
  function lathe(pts, seg) { return new THREE.LatheGeometry(pts.map((a) => new THREE.Vector2(Math.max(0.0005, a[0]), a[1])), seg || 16); }

  function finish() {
    for (const { jn, mat, list } of B.values()) {
      const m = new THREE.Mesh(mergeList(list), mat);
      m.castShadow = true; m.receiveShadow = true; m.name = jn + '_part';
      J[jn].add(m);
    }
    // palm markers, in the arm frame
    const hands = {};
    for (const sd of [1, -1]) {
      const h = new THREE.Object3D();
      h.name = sd > 0 ? 'handL' : 'handR';
      h.position.set(0, -D.handY, D.handZ || 0).applyMatrix4(armFrame(sd));
      J[sd > 0 ? 'armL' : 'armR'].add(h);
      hands[h.name] = h;
    }
    const measure = () => {
      const box = new THREE.Box3(), v = new V3();
      g.updateMatrixWorld(true);
      g.traverse((n) => {
        const p = n.isMesh && n.geometry.attributes.position; if (!p) return;
        for (let i = 0; i < p.count; i++) box.expandByPoint(v.fromBufferAttribute(p, i).applyMatrix4(n.matrixWorld));
      });
      return box;
    };
    // exact height: every joint has zero rest rotation, so scaling joint offsets and geometry is exact
    let box = measure();
    const k = D.H / (box.max.y - box.min.y);
    g.traverse((n) => { if (n === g) return; n.position.multiplyScalar(k); if (n.isMesh) { n.position.set(0, 0, 0); n.geometry.scale(k, k, k); n.geometry.computeBoundingSphere(); } });
    box = measure();
    const c = box.getCenter(new V3());
    g.children.forEach((o) => { o.position.x -= c.x; o.position.y -= box.min.y; o.position.z -= c.z; });
    g.userData.joints = { torso: J.torso, head: J.head, hat: J.hat, armL: J.armL, armR: J.armR, legL: J.legL, legR: J.legR, handL: hands.handL, handR: hands.handR };
    return g;
  }
  const K = { THREE, D, M, put, sym, putArm, arms, putLeg, legs, putHat, symHat, lathe, TRS, J };

  // ---- body kit C: superellipsoid vinyl blocks (sphere vertices remapped into rounded boxes) ----
  K.style = 'C';
  K.fz = 0.014;
  // pxz shapes the plan (1 = round, 0.4 = boxy), py the profile; taper scales the top relative to the bottom
  const sq = (rx, ry, rz, pxz, py, taper, ws, hs) => {
    const q = new THREE.SphereGeometry(1, ws || 12, hs || 8), a = q.attributes.position;
    const f = (t, p) => Math.sign(t) * Math.pow(Math.abs(t), p);
    for (let i = 0; i < a.count; i++) {
      const x = a.getX(i), y = a.getY(i), z = a.getZ(i);
      const k = taper ? 1 + (taper - 1) * (y + 1) / 2 : 1;
      a.setXYZ(i, f(x, pxz) * rx * k, f(y, py) * ry, f(z, pxz) * rz * k);
    }
    q.computeVertexNormals();
    return q;
  };
  K.sq = sq;
  K.blob = (rx, ry, rz, ws, hs) => sq(rx, ry, rz, 0.9, 0.9, 1, ws || 12, hs || 9);
  K.tube = (rBot, rTop, h, seg) => sq(Math.max(rBot, rTop), h / 2, Math.max(rBot, rTop), 1, 0.3, rTop / Math.max(rBot, rTop), seg || 14, 10);
  K.cap = (r, len, seg) => sq(r, len / 2 + r, r, 1, 0.75, 1, seg || 10, 10);
  K.trousers = (mat, o) => {
    const h = o.y0 - o.y1;
    legs(mat, sq(o.r, h / 2 + 0.02, o.r, 0.85, 0.45, 1 / (o.taper || 0.9), 12, 8), [0, (o.y0 + o.y1) / 2, 0]);
  };
  K.boots = (mat, sole, o) => {
    const b = -D.legY, sh = o.soleH || 0.05;
    const shaftH = o.top - (b + 0.08);
    legs(mat, sq(o.r * 1.02, shaftH / 2, o.r * 1.02, 0.8, 0.4, 0.96, 12, 8), [0, b + 0.08 + shaftH / 2, 0]);
    legs(mat, sq(o.w, 0.095, o.len / 2, 0.7, 0.75, 1, 14, 8), [0, b + sh + 0.045, o.toeZ]);
    legs(sole, sq(o.w * 1.06, sh / 2, o.len / 2 * 1.04, 0.6, 0.25, 1, 16, 6), [0, b + sh / 2, o.toeZ]);
    if (o.cuffMat) legs(o.cuffMat, sq(o.r * 1.16, 0.035, o.r * 1.16, 0.8, 0.4, 1, 14, 6), [0, o.top - 0.02, 0]);
  };
  K.coat = (mat, o) => {
    const h = o.y1 - o.y0, sh = o.shH || 0.1, full = h + sh;
    const bk = o.belly ? 1.08 : 1;
    put('torso', mat, sq(o.hemR * bk, full / 2, o.rz * (o.hemR / o.rx) * bk * (o.belly ? 1.06 : 1), 0.62, 0.55, o.rx / o.hemR, 18, 13), [0, o.y0 + full / 2, 0]);
  };
  K.sleeves = (mat, o) => {
    arms(mat, sq(o.r * 1.04, o.len / 2 + 0.02, o.r * 1.04, 0.85, 0.6, 1.0, 10, 8), [0, -o.len / 2 + 0.02, 0]);
    if (o.cuffMat) arms(o.cuffMat, sq(o.r * 1.16, 0.03, o.r * 1.16, 0.85, 0.4, 1, 12, 6), [0, -o.len + 0.03, 0]);
  };
  K.hands = (mat, o) => {
    const y = -D.handY, s = o.s || 1;
    arms(mat, sq(0.04 * s, 0.085 * s, 0.068 * s, 0.7, 0.8, 1, 10, 8), [0, y + 0.0, 0]);
    arms(mat, sq(0.022 * s, 0.045 * s, 0.022 * s, 1, 0.8, 1, 8, 8), [-0.022 * s, y + 0.01, 0.065 * s], [0.6, 0, -0.5]);
  };
  K.hairCap = (mat, hd, th, k, ph0, phL) => {
    const q = new THREE.SphereGeometry(1, 14, 8, ph0 === undefined ? Math.PI : ph0, phL || Math.PI, 0, Math.PI * th), a = q.attributes.position;
    const f = (t, p) => Math.sign(t) * Math.pow(Math.abs(t), p), tp = 1 - (hd.chin || 0) * 2;
    for (let i = 0; i < a.count; i++) { const x = a.getX(i), y = a.getY(i), z = a.getZ(i), kk = 1 + (tp - 1) * (y + 1) / 2; a.setXYZ(i, f(x, 0.86) * kk, f(y, 0.86), f(z, 0.86) * kk); }
    q.computeVertexNormals();
    put('head', mat, q, [0, hd.cy, 0], null, [hd.rx * k, hd.ry * k, hd.rz * k]);
  };
  K.headBase = (mat, o) => {
    put('head', mat, sq(o.rx, o.ry, o.rz, 0.86, 0.86, 1 - (o.chin || 0) * 2, 18, 13), [0, o.cy, 0]);
    put('head', mat, K.tube(0.06, 0.06, 0.1, 10), [0, 0.03, 0]);
    sym('head', mat, K.blob(0.03, 0.045, 0.025, 8, 6), [o.rx * 0.98, o.cy - 0.01, -0.01]);
  };

  dress(K);
  return finish();
}
